Sandbox/07-02-2025/force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sandbox/07-02-2025/force-app/main/default/objects/Revenue_Share_Mapping__c/Revenue_Share_Mapping__c.object-meta.xml
<CustomObject>
    <label>Revenue Share Mapping</label>
    <nameField>
        <displayFormat>RS-{0000000000}</displayFormat>
        <label>Revenue Share Mapping Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Share Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sandbox/01-02-2025/force-app/main/default/objects/Revenue_Share_Mapping__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Target Country</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Supply_Database__c/Supply_Database__c.object-meta.xml
<CustomObject>
    <label>Supply Database</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Supply Database Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supply Databases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Production/01-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Data_Supplier__c.field-meta.xml
<CustomField>
    <fullName>Data_Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Data Supplier Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supply Databases</relationshipLabel>
    <relationshipName>Supply_Databases</relationshipName>
    <type>Lookup</type>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Data_Supplier_Raw__c.field-meta.xml
<CustomField>
    <fullName>Data_Supplier_Raw__c</fullName>
    <description>Data Supplier Raw Input converted to Upper Case for Comparison.</description>
    <inlineHelpText>Data Supplier Raw Input converted to Upper Case</inlineHelpText>
    <label>Data Supplier Raw</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Segment_Name_Supply_Raw_Original__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name_Supply_Raw_Original__c</fullName>
    <label>Segment Name (Supply) Raw Original</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/04-19-2025/force-app/main/default/classes/RevenueSharingMappingTest.cls
@isTest 
    public with sharing class RevenueSharingMappingTest {
        Static testmethod void RevenueSharingMappingTest(){
            
            Supply_Database__c Sup = new Supply_Database__c();
            Sup.Segment_Name_Supply_Raw_Original__c = 'Richard';
            Sup.Data_Supplier_Raw__c ='Gear';
            insert Sup;
            
            Supply_Database__c S = new Supply_Database__c();
            S.Data_Supplier_Raw__c = 'Richard';
            S.Segment_Name_Supply_Raw_Original__c ='ABC';
            insert S;
            
            Revenue_Share_Mapping__c rev = new Revenue_Share_Mapping__c();
            rev.Data_Supplier__c='Earned';
            rev.Country__c='India';
        }
}