Sandbox/07-02-2025/force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sandbox/02-12-2025/force-app/main/default/objects/Country__c/fields/Master_Geography_Code__c.field-meta.xml
<CustomField>
    <fullName>Master_Geography_Code__c</fullName>
    <label>Master Geography Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Country_Monthly_Global__c/Country_Monthly_Global__c.object-meta.xml
<CustomObject>
    <label>Country Monthly Global</label>
    <nameField>
        <displayFormat>CMG-{0000000000}</displayFormat>
        <label>Country Months Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Country Monthly Global</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Production/01-02-2025/force-app/main/default/objects/Country_Monthly_Global__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Country Monthly Global</relationshipLabel>
    <relationshipName>Country_Monthly_Global</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Country_Monthly_Global__c/fields/Master_Geography_Code__c.field-meta.xml
<CustomField>
    <fullName>Master_Geography_Code__c</fullName>
    <label>Master Geography Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/classes/CountryMonthlyGlobalTest.cls
@isTest
public class CountryMonthlyGlobalTest
{
    static testmethod void myTest1(){
        
        country__c cont=new country__c();
        cont.name='India';
        insert cont;
        
        Country_Monthly_Global__c con = new Country_Monthly_Global__c();
        con.Country_Name__c= 'India';
        con.Date__c=date.today();
        con.Master_Geography_Code__c='ABC';
        con.Country__c=cont.Id;
        insert con;
        
        
        
    }
    /*static testmethod void CountryMonthlyGlobalTest(){
        try{
            Country_Monthly_Global__c con = new Country_Monthly_Global__c();
        con.Country_Name__c= 'India';
        insert con;}catch(Exception e){}
    }*/
}