Sandbox/02-12-2025/force-app/main/default/objects/Account/recordTypes/Advertiser.recordType-meta.xml
<RecordType>
    <fullName>Advertiser</fullName>
    <active>true</active>
    <description>Advertiser Accounts</description>
    <label>Advertiser</label>
</RecordType>

Sandbox/02-12-2025/force-app/main/default/objects/Advertiser_Mapping__c/Advertiser_Mapping__c.object-meta.xml
<CustomObject>
    <label>Advertiser Mapping</label>
    <nameField>
        <displayFormat>AM -{0000000000}</displayFormat>
        <label>Advertiser Mapping Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advertiser Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sandbox/01-02-2025/force-app/main/default/objects/Advertiser_Mapping__c/fields/Advertiser_Name__c.field-meta.xml
<CustomField>
    <fullName>Advertiser_Name__c</fullName>
    <label>Advertiser Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Advertiser_Mapping__c/fields/Advertiser_Raw__c.field-meta.xml
<CustomField>
    <fullName>Advertiser_Raw__c</fullName>
    <label>Advertiser Raw</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/classes/AdvMappingTest.cls
@isTest
private class AdvMappingTest {
static testMethod void AdvMappingTest() {
 

        //create Advertiser Account for mapping
        Account Acc = new Account (Name='Test Account', RecordTypeId='01290000000iUro');
        Insert Acc;
       
       //create Advertiser Mapping Record for mapping
        Advertiser_Mapping__c AdvMapping = new Advertiser_Mapping__c (Advertiser_Raw__c='TEST', Advertiser_Name__c='Test Account');
        Insert AdvMapping;
        Advertiser_Mapping__c AdvMappingException = new Advertiser_Mapping__c (Advertiser_Raw__c='TESTEXCEPTION', Advertiser_Name__c='Test Advertiser Exception');
        Insert AdvMappingException;
       }
    }