Sandbox/02-12-2025/force-app/main/default/objects/Account/recordTypes/Advertiser.recordType-meta.xml
<RecordType>
    <fullName>Advertiser</fullName>
    <active>true</active>
    <description>Advertiser Accounts</description>
    <label>Advertiser</label>
</RecordType>

Sandbox/02-12-2025/force-app/main/default/objects/Account/recordTypes/Buyer.recordType-meta.xml
<RecordType>
    <fullName>Buyer</fullName>
    <active>true</active>
    <description>Buyer Accounts</description>
    <label>Buyer</label>
</RecordType>

Sandbox/02-12-2025/force-app/main/default/objects/Opportunity/fields/Advertiser_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Advertiser_Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advertiser Account Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Advertiser</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advertiser Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Opportunity/fields/Opportunity_ID__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_ID__c</fullName>
    <formula>CASESAFEID(Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity ID</label>
    <type>Text</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Segment_Brief_Tracking__c/Segment_Brief_Tracking__c.object-meta.xml
<CustomObject>
    <description>Tracks every Segment Brief sent to new/existing clients.</description>
    <label>Segment Brief Tracking</label>
    <nameField>
        <label>Segment Brief Tracking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segment Briefs Tracking</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sandbox/07-04-2025/force-app/main/default/objects/Segment_Brief_Tracking__c/fields/Advertiser_Account__c.field-meta.xml
<CustomField>
    <fullName>Advertiser_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advertiser Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Segment Briefs Tracking</relationshipLabel>
    <relationshipName>Segment_Briefs_Tracking_AdvAcc</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Segment_Brief_Tracking__c/fields/Buyer_Account__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Buyer Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Segment Briefs Tracking (Buyer Account)</relationshipLabel>
    <relationshipName>Segment_Briefs_Tracking_BuyAcc</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Segment_Brief_Tracking__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Segment Briefs Tracking</relationshipLabel>
    <relationshipName>Segment_Briefs_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Segment_Brief_Tracking__c/fields/Opportunity_ID__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_ID__c</fullName>
    <label>Opportunity ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Segment_Brief_Tracking__c/fields/Segment_Error__c.field-meta.xml
<CustomField>
    <fullName>Segment_Error__c</fullName>
    <label>Segment Error</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Segment_Brief_Tracking__c/fields/Segment_Name__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This links the briefs to our sales numbers via the Segment Name</description>
    <label>Segment Category Mapping</label>
    <referenceTo>Segment_Category_Mapping__c</referenceTo>
    <relationshipLabel>Segment Briefs Tracking</relationshipLabel>
    <relationshipName>Segment_Briefs_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Segment_Brief_Tracking__c/fields/Segment_Name_For_Upload__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name_For_Upload__c</fullName>
    <label>Segment Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Segment_Category_Mapping__c/Segment_Category_Mapping__c.object-meta.xml
<CustomObject>
    <label>Segments Database</label>
    <nameField>
        <displayFormat>SC-{0000000000}</displayFormat>
        <label>Segment Category Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments Database</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Production/01-02-2025/force-app/main/default/objects/Segment_Category_Mapping__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity for Custom Segments</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Custom Segments</relationshipLabel>
    <relationshipName>Segments_Database</relationshipName>
    <type>Lookup</type>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Segment_Category_Mapping__c/fields/Segment_Name__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name__c</fullName>
    <externalId>true</externalId>
    <label>Segment Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/classes/SegmentBriefTrackingTriggerHandler.cls
public class SegmentBriefTrackingTriggerHandler {
    
    public static void onBeforeInsertUpdate(List<Segment_Brief_Tracking__c> segmentBriefList) {
        
        //Create a Set of all Opportunities to be Uploaded
        Set<Id> OpportunityIDs = new Set<Id>();
        
        //Create a Set of all the Segment Names to be Uploaded
        Set<String> SegmentNames = new Set<String>();

        //Map Segment Name for Upload to Segment Taxonomy Name
        Map<String,Segment_Category_Mapping__c> mastersheet = new Map<String,Segment_Category_Mapping__c>();

        for(Segment_Brief_Tracking__c segbrieftrack : segmentBriefList) {
            OpportunityIDs.add(segbrieftrack.Opportunity_ID__c);

            if(String.isNotBlank(segbrieftrack.Segment_Name_For_Upload__c)){
                SegmentNames.add(segbrieftrack.Segment_Name_For_Upload__c);
            }
        }

        //Query and Map Opportunity
        Map<Id,Opportunity> Opportunities = new Map<Id,Opportunity>([Select Id, 
                                                                            Advertiser_Account_Name__c, 
                                                                            AccountID from Opportunity 
                                                                            where Id in : OpportunityIDs]);

        for(Segment_Category_Mapping__c objSegmentCM : [Select Id, 
                                                                Segment_Name__c FROM Segment_Category_Mapping__c 
                                                                WHERE Segment_Name__c IN :SegmentNames]) {
            mastersheet.put(objSegmentCM.Segment_Name__c, objSegmentCM);
        }

        //Set Opportunity, Buyer Account and Advertiser Account
        //Add Segment Category Mapping ID to Segment Brief Tracking Record
        for(Segment_Brief_Tracking__c segbrieftrack : segmentBriefList) {
            
            if(!Opportunities.isEmpty() && Opportunities.containsKey(segbrieftrack.Opportunity_ID__c)) {
                segbrieftrack.Opportunity__c = Opportunities.get(segbrieftrack.Opportunity_ID__c)?.Id;
                segbrieftrack.Buyer_Account__c = Opportunities.get(segbrieftrack.Opportunity_ID__c)?.AccountID;
                segbrieftrack.Advertiser_Account__c = Opportunities.get(segbrieftrack.Opportunity_ID__c)?.Advertiser_Account_Name__c;
            }

            if(segbrieftrack.Segment_Name_For_Upload__c!=null && segbrieftrack.Segment_Name_For_Upload__c != '' && 
                (!mastersheet.isEmpty() && mastersheet.containsKey(segbrieftrack.Segment_Name_For_Upload__c))) {
                segbrieftrack.Segment_Name__c = mastersheet.get(segbrieftrack.Segment_Name_For_Upload__c)?.Id;
            }
            else {
                segbrieftrack.Segment_Name__c = null;
                segbrieftrack.Segment_Error__c='This segment does not exist.';
            }
        }
    }
}