Sandbox/02-12-2025/force-app/main/default/objects/Account/recordTypes/Advertiser.recordType-meta.xml
<RecordType>
    <fullName>Advertiser</fullName>
    <active>true</active>
    <description>Advertiser Accounts</description>
    <label>Advertiser</label>
</RecordType>

Sandbox/07-02-2025/force-app/main/default/objects/Advertiser_Mapping__c/Advertiser_Mapping__c.object-meta.xml
<CustomObject>
    <label>Advertiser Mapping</label>
    <nameField>
        <displayFormat>AM -{0000000000}</displayFormat>
        <label>Advertiser Mapping Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advertiser Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sandbox/02-12-2025/force-app/main/default/objects/Advertiser_Mapping__c/fields/Advertiser_Account__c.field-meta.xml
<CustomField>
    <fullName>Advertiser_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Advertiser Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Advertiser</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Advertiser Mappings</relationshipLabel>
    <relationshipName>Advertiser_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Advertiser_Mapping__c/fields/Advertiser_Error__c.field-meta.xml
<CustomField>
    <fullName>Advertiser_Error__c</fullName>
    <label>Advertiser Error</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Advertiser_Mapping__c/fields/Advertiser_Name__c.field-meta.xml
<CustomField>
    <fullName>Advertiser_Name__c</fullName>
    <label>Advertiser Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/classes/AdvertiserMappingTriggerHandler.cls
public class AdvertiserMappingTriggerHandler {

    public static void onBeforeInsertUpdate(List<Advertiser_Mapping__c> advMappingList) {

        Set<String> AdvNames = new Set<String>();
        Map<String,Account> AdvertiserAccountName = new Map<String,Account>(); 

        for(Advertiser_Mapping__c AdvMapping : advMappingList) {

            if(String.isNotBlank(AdvMapping.Advertiser_Name__c)) {
                AdvNames.add(AdvMapping.Advertiser_Name__c);
            }
        }

        if(!AdvNames.isEmpty()) {
            
            for(Account objAccount : [Select ID,Name FROM Account WHERE Name IN : AdvNames AND RecordType.Name='Advertiser']) {
                AdvertiserAccountName.put(objAccount.Name, objAccount);
            }  

            for(Advertiser_Mapping__c AdvMapping : advMappingList) {

                if(String.isNotBlank(AdvMapping.Advertiser_Name__c) && 
                (!AdvertiserAccountName.isEmpty() && AdvertiserAccountName.containsKey(AdvMapping.Advertiser_Name__c)) && 
                AdvMapping.Advertiser_Account__c == null) {
                    AdvMapping.Advertiser_Account__c = AdvertiserAccountName.get(AdvMapping.Advertiser_Name__c)?.Id;
                    AdvMapping.Advertiser_Error__c = null;
                }
            }
        }
    }
}