Sandbox/02-12-2025/force-app/main/default/objects/Supply_Database__c/Supply_Database__c.object-meta.xml
<CustomObject>
    <label>Supply Database</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Supply Database Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supply Databases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sandbox/02-12-2025/force-app/main/default/objects/Supply_Database__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date of the Buy</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/classes/ProcessSupplyDatabaseScriptBatchTest.cls
@isTest
public class ProcessSupplyDatabaseScriptBatchTest {
    static testmethod void testMethod1(){
        Supply_Database__c sd=new Supply_Database__c();
        sd.Date__c=date.today();
        insert sd;
        ProcessSupplyDatabaseScriptBatch obj=new ProcessSupplyDatabaseScriptBatch(date.today(),'test obj');
        test.startTest();
        DataBase.executeBatch(obj);
        test.stopTest();
    }
}