Sandbox/02-12-2025/force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Production/01-02-2025/force-app/main/default/objects/Country__c/fields/Country_Code_2__c.field-meta.xml
<CustomField>
    <fullName>Country_Code_2__c</fullName>
    <label>Country Code 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Country__c/fields/Master_Geography_Code__c.field-meta.xml
<CustomField>
    <fullName>Master_Geography_Code__c</fullName>
    <label>Master Geography Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Country_Monthly_Global__c/Country_Monthly_Global__c.object-meta.xml
<CustomObject>
    <label>Country Monthly Global</label>
    <nameField>
        <displayFormat>CMG-{0000000000}</displayFormat>
        <label>Country Months Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Country Monthly Global</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Production/01-02-2025/force-app/main/default/objects/Country_Monthly_Global__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Country Monthly Global</relationshipLabel>
    <relationshipName>Country_Monthly_Global</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Country_Monthly_Global__c/fields/Master_Geography_Code__c.field-meta.xml
<CustomField>
    <fullName>Master_Geography_Code__c</fullName>
    <label>Master Geography Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/classes/CountryMonthlyGlobalTriggerHandler.cls
public class CountryMonthlyGlobalTriggerHandler {
    
    public static void onBeforeInsertUpdate(List<Country_Monthly_Global__c> countryMonthlyList) {
        
        Set<String> cmgCountryCodes = new Set<String>();
        //Set<String> cmgCountryCodes2 = new Set<String>();
        //Set<String> countryLookup = new Set<String>();
        //Set<Date> cmgDate = new Set<Date>();
        Set<Date> cmgDate1 = new Set<Date>();
        Map<String, Country__c> countryMap = new Map<String, Country__c>();

        for(Country_Monthly_Global__c cmg : countryMonthlyList) {
            if(cmg.Country_Name__c != null && cmg.Country_Name__c != '') {
                cmgCountryCodes.add(cmg.Country_Name__c);
            }
            if(cmg.Date__c != null) {
                cmgDate1.add(cmg.Date__c);                
            }
        }
        System.debug('cmgCountryCodes-------->'+cmgCountryCodes);
        for(Country__c c:[SELECT Id, Name, Country_Code_2__c FROM Country__c WHERE Name IN : cmgCountryCodes]) {
            countryMap.put(c.Name.toUpperCase() , c);
        }

        for(Country_Monthly_Global__c cmg : countryMonthlyList) {
            if(cmg.Country_Name__c != null && cmg.Country_Name__c != '' && 
            (!countryMap.isEmpty() && countryMap.containsKey(cmg.Country_Name__c.toUpperCase()))) {
                
                cmg.Country__c = countryMap.get(cmg.Country_Name__c.toUpperCase())?.Id;
                cmg.Master_Geography_Code__c = countryMap.get(cmg.Country_Name__c.toUpperCase())?.Country_Code_2__c;
     
                //Commented this out because it doesn't do anything - June 13 2024
                /*if(cmg1.Date__c != null){
                    cmgDate.add(cmg1.Date__c);
                }
                System.debug('cmg1.country----@@'+cmg1.Country__c);
                if(cmg1.Country__c != null){
                    countryLookup.add(cmg1.Country__c);
                }
                System.debug('cmg1.Master_Geography_Code__c----@@'+cmg1.Master_Geography_Code__c);
                if(cmg1.Master_Geography_Code__c != null && cmg1.Master_Geography_Code__c!= ''){
                    cmgCountryCodes2.add(cmg1.Master_Geography_Code__c);
                }*/          
            }
        }
    }
}