Sandbox/07-04-2025/force-app/main/default/objects/Sales_Database__c/Sales_Database__c.object-meta.xml
<CustomObject>
    <label>Sales Database</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Sales Database Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Databases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sandbox/01-02-2025/force-app/main/default/objects/Sales_Database__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Sales_Database__c/fields/Segment_Category_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Segment_Category_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segment Category Mapping</label>
    <referenceTo>Segment_Category_Mapping__c</referenceTo>
    <relationshipLabel>Sales Databases</relationshipLabel>
    <relationshipName>Sales_Databases</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Sales_Database__c/fields/Segment_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Segment_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segment Mapping</label>
    <referenceTo>Segment_Mapping__c</referenceTo>
    <relationshipLabel>Sales Databases</relationshipLabel>
    <relationshipName>Sales_Databases</relationshipName>
    <type>Lookup</type>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Sales_Database__c/fields/Segment_Name__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name__c</fullName>
    <formula>Segment_Category_Mapping__r.Segment_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Segment Name</label>
    <type>Text</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Sales_Database__c/fields/Target_Country_Raw__c.field-meta.xml
<CustomField>
    <fullName>Target_Country_Raw__c</fullName>
    <externalId>true</externalId>
    <label>Target Country Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Segment_Category_Mapping__c/Segment_Category_Mapping__c.object-meta.xml
<CustomObject>
    <label>Segments Database</label>
    <nameField>
        <displayFormat>SC-{0000000000}</displayFormat>
        <label>Segment Category Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments Database</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Production/01-02-2025/force-app/main/default/objects/Segment_Category_Mapping__c/fields/Segment_Key_Raw__c.field-meta.xml
<CustomField>
    <fullName>Segment_Key_Raw__c</fullName>
    <formula>UPPER( Segment_Code__c )</formula>
    <label>Segment Key Raw</label>
    <type>Text</type>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Segment_Category_Mapping__c/fields/Segment_Name__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name__c</fullName>
    <externalId>true</externalId>
    <label>Segment Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Segment_Mapping__c/Segment_Mapping__c.object-meta.xml
<CustomObject>
    <label>Segment Mapping</label>
    <nameField>
        <displayFormat>SM-{0000000000}</displayFormat>
        <label>Segment Mapping Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segment Mappings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Production/01-02-2025/force-app/main/default/objects/Segment_Mapping__c/fields/Segment_Category_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Segment_Category_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segment Category Mapping</label>
    <referenceTo>Segment_Category_Mapping__c</referenceTo>
    <relationshipName>Segment_Mapping</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Segment_Mapping__c/fields/Segment_Name_Supply_Raw__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name_Supply_Raw__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Please upload SEGMENT KEY in this field (ALL CAPS) for supply data from October 1, 2016 onwards.</inlineHelpText>
    <label>Segment Name (Supply) Raw</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Segment_Monthly_Global__c/Segment_Monthly_Global__c.object-meta.xml
<CustomObject>
    <label>Segment Monthly Global</label>
    <nameField>
        <displayFormat>SMG-{0000000000}</displayFormat>
        <label>Segment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segment Monthly Global</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sandbox/01-02-2025/force-app/main/default/objects/Segment_Monthly_Global__c/fields/Country_Raw__c.field-meta.xml
<CustomField>
    <fullName>Country_Raw__c</fullName>
    <label>Country Raw</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Segment_Monthly_Global__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <description>Revenue to be aggregated from Segment Transaction Object, Sales Revenue Rollup field, for Month and Segment.</description>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Segment_Monthly_Global__c/fields/Segment_Category_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Segment_Category_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segment Category Mapping</label>
    <referenceTo>Segment_Category_Mapping__c</referenceTo>
    <relationshipLabel>Segment Monthly Global</relationshipLabel>
    <relationshipName>Segment_Monthly_Global</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Segment_Monthly_Global__c/fields/Segment_Key_Raw__c.field-meta.xml
<CustomField>
    <fullName>Segment_Key_Raw__c</fullName>
    <label>Segment Key Raw</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Segment_Monthly_Global__c/fields/Segment_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Segment_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segment Mapping</label>
    <referenceTo>Segment_Mapping__c</referenceTo>
    <relationshipLabel>Segment Monthly Global</relationshipLabel>
    <relationshipName>Segment_Monthly_Global</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Segment_Monthly_Global__c/fields/Segment_Name__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name__c</fullName>
    <formula>Segment_Category_Mapping__r.Segment_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Segment Name</label>
    <type>Text</type>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Segment_Monthly_Global__c/fields/Segment_Name_Supply_Raw__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name_Supply_Raw__c</fullName>
    <label>Segment Name (Supply) Raw</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Segment_Monthly_Global__c/fields/Segment_Name_Supply_Raw_Original__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name_Supply_Raw_Original__c</fullName>
    <label>Segment Name (Supply) Raw Original</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/classes/SegmentMonthlyGlobalTriggerHandler.cls
public class SegmentMonthlyGlobalTriggerHandler {
    
    public static void onBeforeInsertUpdate(List<Segment_Monthly_Global__c> smgList) {
        
        Set<String> segmentReachList = new Set<String>();
        Set<String> segmentRawList = new Set<String>();
        Map<String,Segment_Category_Mapping__c> msmMap = new Map<String,Segment_Category_Mapping__c>();
        Map<String,Segment_Mapping__c> segMap = new map<String,Segment_Mapping__c>();
        Map<String,String> mapSegMapSegCats = new Map<String,String>(); 

        Date tempOctDt = Date.newInstance(2016, 10, 01);

        for(Segment_Monthly_Global__c smg : smgList) {
            
            System.debug('tempOctDt---@@'+tempOctDt);
            //  If Date < 1/10/2016
            if(String.isNotBlank(smg.Segment_Name_Supply_Raw__c) && smg.Date__c < tempOctDt) {
                smg.Segment_Name_Supply_Raw__c = smg.Segment_Name_Supply_Raw_Original__c.toUpperCase();
                segmentReachList.add(smg.Segment_Name_Supply_Raw__c);
            }
            //IF Date >= 1/10/2016 
            else if(String.isNotBlank(smg.Segment_Key_Raw__c) && smg.Date__c >= tempOctDt){
                smg.Segment_Name_Supply_Raw__c = smg.Segment_Key_Raw__c;
                segmentReachList.add(smg.Segment_Key_Raw__c);            
            }
        }  
        // End..Create Segment Name or Segment Key Maps based on Date Range - < or >= 10th Oct 2016.....
        System.debug('segmentReachList----@@'+segmentReachList);
        // Start..Create Segment Mapping and Category Mapping Master records Maps based on the available input records......
        for(Segment_Mapping__c sm : [SELECT Id,
                                            Segment_Name__c,
                                            Segment_Name_Supply_Raw__c FROM Segment_Mapping__c 
                                            WHERE Segment_Name_Supply_Raw__c IN : segmentReachList]) {
            segMap.put(sm.Segment_Name_Supply_Raw__c,sm);
            segmentRawList.add(sm.Segment_Name__c);
            mapSegMapSegCats.put(sm.Segment_Name_Supply_Raw__c,sm.Segment_Name__c);
        }  
        
        for(Segment_Category_Mapping__c msm : [SELECT Id,
                                                        Name,
                                                        Segment_Name__c FROM Segment_Category_Mapping__c 
                                                        WHERE Segment_Name__c IN : segmentRawList]){
            msmMap.put(msm.Segment_Name__c,msm);
        }
        // End..Create Segment Mapping and Category Mapping Master records Maps based on the available input records......

        // Start Populate the Segment Mapping and Category Mapping Lookups into the Segment Monthly Global Records..
        for(Segment_Monthly_Global__c smg : smgList) {
            if(!segMap.isEmpty() && segMap.containsKey(smg.Segment_Name_Supply_Raw__c)) {
                //  If Date < 1/10/2016
                if(smg.Segment_Name_Supply_Raw__c != null && smg.Segment_Name_Supply_Raw__c != '' && 
                segMap.get(smg.Segment_Name_Supply_Raw__c) != null && smg.Date__c < tempOctDt) {
                    smg.Segment_Mapping__c = segMap.get(smg.Segment_Name_Supply_Raw__c).Id; 
                    String segName = mapSegMapSegCats.get(smg.Segment_Name_Supply_Raw__c);
                    smg.Segment_Category_Mapping__c = msmMap.get(segName).Id;    
                }
                //IF Date >= 1/10/2016
                else if(String.isNotBlank(smg.Segment_Key_Raw__c) && segMap.get(smg.Segment_Key_Raw__c) != null && smg.Date__c >= tempOctDt){
                    smg.Segment_Mapping__c = segMap.get(smg.Segment_Key_Raw__c).Id; 
                    String segName = mapSegMapSegCats.get(smg.Segment_Key_Raw__c);
                    smg.Segment_Category_Mapping__c = msmMap.get(segName) != null ? msmMap.get(segName).Id : null; 
                }
            }
        }
    }

    public static void onAfterInsertUpdate(Map<Id, Segment_Monthly_Global__c> newMap, Map<Id, Segment_Monthly_Global__c> oldMap) {
        
        if(!TriggerUtility.inFutureContext1) {
            
            //Set<String> segmentName = new Set<String>();
            Set<Date> month = new Set<Date>();
            Set<String> setSegCats = new Set<String>();

            List<Segment_Monthly_Global__c> dsl2Update = new List<Segment_Monthly_Global__c>(); 
            
            Map<String, List<Sales_Database__c>> salesDatabaseMap = new Map<String, List<Sales_Database__c>>();

            for(Segment_Monthly_Global__c smg2 : newMap.values()){
                /*if(smg2.Segment_Name__c != null) {
                    segmentName.add(smg2.Segment_Name__c);
                }*/
                if(smg2.Date__c != null) {
                    month.add(smg2.Date__c);
                }
                if(smg2.Segment_Category_Mapping__c != null) {
                    setSegCats.add(smg2.Segment_Category_Mapping__c); 
                }
            }        
                     
            //Query all possible matching Sales Database Records. 
            System.debug('setSegCats---@@'+setSegCats);
            System.debug('month---@@'+month);

            for(Sales_Database__c sd : [SELECT Id,
                                                Name,
                                                Target_Country_Raw__c,
                                                Segment_Name__c,
                                                Revenue__c,
                                                Date__c,
                                                Segment_Category_Mapping__c 
                                                FROM Sales_Database__c 
                                                WHERE Segment_Category_Mapping__c IN:setSegCats 
                                                AND Date__c IN: month 
                                                AND IsDeleted = false]) {

                if(sd.Segment_Category_Mapping__c != null) {                                    
                    if(!salesDatabaseMap.containsKey(sd.Segment_Category_Mapping__c)) {
                        salesDatabaseMap.put(sd.Segment_Category_Mapping__c, new List<Sales_Database__c>{sd});
                    }
                    else {
                        salesDatabaseMap.get(sd.Segment_Category_Mapping__c).add(sd);
                    }
                }
            }

            //Start Loop all incoming Segment Monthly Global records and loop through the relevant Sales Database records and aggregate Revenue and stamp.                                             
            for(Segment_Monthly_Global__c pm : [SELECT Id,
                                                        Segment_Name__c,
                                                        Date__c,
                                                        Country_Raw__c,
                                                        Revenue__c,
                                                        Segment_Category_Mapping__c 
                                                        FROM Segment_Monthly_Global__c 
                                                        WHERE Id IN: newMap.keyset()]) { 
                Double revenues = 0.0;

                if(!salesDatabaseMap.isEmpty() && salesDatabaseMap.containsKey(pm.Segment_Category_Mapping__c)) {
                    for(Sales_Database__c sd : salesDatabaseMap.get(pm.Segment_Category_Mapping__c)) {
                        if('Global'.equalsignorecase(pm.Country_Raw__c) || pm.Country_Raw__c == '' || pm.Country_Raw__c == null) {
                            if(pm.Date__c == sd.Date__c) {
                                revenues += sd.Revenue__c != null?sd.Revenue__c:0.0;                        
                            }
                        }
                        else {
                            if(pm.Date__c == sd.Date__c && pm.Country_Raw__c == sd.Target_Country_Raw__c) { 
                                revenues += sd.Revenue__c != null?sd.Revenue__c:0.0;                        
                            }
                        }
                    }
                    pm.Revenue__c = revenues;
                    dsl2Update.add(pm);
                }
            }
             //End Loop all incoming Segment Monthly Global records and loop through the relevant Sales Database records and aggregate Revenue and stamp
    
            TriggerUtility.inFutureContext1 = true;
            if(!dsl2Update.isEmpty()) update dsl2Update;     // Update all the inserted and updated SMG records. 
        }
    }
}