Sandbox/07-04-2025/force-app/main/default/objects/Sales_Database__c/Sales_Database__c.object-meta.xml
<CustomObject>
    <label>Sales Database</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Sales Database Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Databases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sandbox/07-02-2025/force-app/main/default/objects/Sales_Database__c/fields/Advertiser_Error__c.field-meta.xml
<CustomField>
    <fullName>Advertiser_Error__c</fullName>
    <label>Advertiser Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Sales_Database__c/fields/Advertiser_Raw__c.field-meta.xml
<CustomField>
    <fullName>Advertiser_Raw__c</fullName>
    <label>Advertiser Seat Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Sales_Database__c/fields/Buyer_Country_Raw__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Country_Raw__c</fullName>
    <label>Buyer Country Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Sales_Database__c/fields/Buyer_Error__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Error__c</fullName>
    <label>Buyer Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Sales_Database__c/fields/Buyer_Raw__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Raw__c</fullName>
    <label>Client Seat Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Sales_Database__c/fields/Date_Invoiced__c.field-meta.xml
<CustomField>
    <fullName>Date_Invoiced__c</fullName>
    <label>Date Invoiced</label>
    <type>Date</type>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Sales_Database__c/fields/Platform_Raw_Original__c.field-meta.xml
<CustomField>
    <fullName>Platform_Raw_Original__c</fullName>
    <label>Platform Raw Original</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Sales_Database__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Sales_Database__c/fields/Segment_Category_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Segment_Category_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segment Category Mapping</label>
    <referenceTo>Segment_Category_Mapping__c</referenceTo>
    <relationshipLabel>Sales Databases</relationshipLabel>
    <relationshipName>Sales_Databases</relationshipName>
    <type>Lookup</type>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Sales_Database__c/fields/Segment_Name__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name__c</fullName>
    <formula>Segment_Category_Mapping__r.Segment_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Segment Name</label>
    <type>Text</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Sales_Database__c/fields/Segment_Name_Error__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name_Error__c</fullName>
    <label>Segment Name Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Sales_Database__c/fields/Segment_Name_Sales_Raw__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name_Sales_Raw__c</fullName>
    <label>Segment Name (Sales) Raw</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Segment_Category_Mapping__c/Segment_Category_Mapping__c.object-meta.xml
<CustomObject>
    <label>Segments Database</label>
    <nameField>
        <displayFormat>SC-{0000000000}</displayFormat>
        <label>Segment Category Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments Database</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Production/01-02-2025/force-app/main/default/objects/Segment_Category_Mapping__c/fields/Segment_Name__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name__c</fullName>
    <externalId>true</externalId>
    <label>Segment Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Supply_Database__c/Supply_Database__c.object-meta.xml
<CustomObject>
    <label>Supply Database</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Supply Database Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supply Databases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sandbox/07-04-2025/force-app/main/default/objects/Supply_Database__c/fields/Data_Supplier_Error__c.field-meta.xml
<CustomField>
    <fullName>Data_Supplier_Error__c</fullName>
    <description>Data Supplier Mapping Not Found</description>
    <inlineHelpText>Data Supplier Mapping Not Found</inlineHelpText>
    <label>Data Supplier Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Data_Supplier_Raw__c.field-meta.xml
<CustomField>
    <fullName>Data_Supplier_Raw__c</fullName>
    <description>Data Supplier Raw Input converted to Upper Case for Comparison.</description>
    <inlineHelpText>Data Supplier Raw Input converted to Upper Case</inlineHelpText>
    <label>Data Supplier Raw</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Supply_Database__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date of the Buy</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Supply_Database__c/fields/Segment_Category_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Segment_Category_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Join to Segment Category Mapping</description>
    <inlineHelpText>Join to Segment Category Mapping through Segment ID.</inlineHelpText>
    <label>Segment Category Mapping</label>
    <referenceTo>Segment_Category_Mapping__c</referenceTo>
    <relationshipLabel>Supply Databases</relationshipLabel>
    <relationshipName>Supply_Databases</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Supply_Database__c/fields/Segment_Name_Error__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name_Error__c</fullName>
    <description>Segment Mapping Not Found, between Segment ID and Master Mapping Keys; Segment Name.</description>
    <inlineHelpText>Segment Mapping Not Found, between Segment ID and Master Mapping Keys; Segment Name.</inlineHelpText>
    <label>Segment Name Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Supply_Database__c/fields/Segment_Name_Supply_Raw__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name_Supply_Raw__c</fullName>
    <label>Segment Name (Supply) Raw</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/classes/Invoke_UpdateSegmentRevenueClassTest.cls
@isTest
public with sharing class Invoke_UpdateSegmentRevenueClassTest {

    @TestSetup
    static void makeData(){
        Sales_Database__c sd = new Sales_Database__c();
        sd.Buyer_Error__c ='acd';
        sd.Buyer_Raw__c = 'abc';
        sd.Buyer_Country_Raw__c ='abc';
        sd.Platform_Raw_Original__c ='abc';
        sd.Date__c = System.today();
        sd.Date_Invoiced__c = System.today();
        sd.Segment_Name_Error__c ='abc';
        sd.Segment_Name_Sales_Raw__c='abc';
        sd.Revenue__c = 1;
        sd.Advertiser_Error__c ='abc';
        sd.Advertiser_Raw__c ='abc';
        
        insert sd;
        
        Segment_Category_Mapping__c sc = new Segment_Category_Mapping__c();
        sc.Segment_Name__c = 'abc';
        insert sc;
        
        Supply_Database__c   sdd = new Supply_Database__c ();
        sdd.Data_Supplier_Error__c = 'abc';
        sdd.Date__c = Date.valueOf('2024-10-01');
        sdd.Segment_Name_Error__c ='abc';
        sdd.Data_Supplier_Raw__c = 'adc';
        sdd.Segment_Name_Supply_Raw__c='abc';
        sdd.Segment_Category_Mapping__c = sc.id;
        //sdd.Segment_Name__c ='abc';
        insert sdd;
    }

    @isTest
    static void scenario(){

        List<Invoke_UpdateSegmentRevenueClass.FlowInput> inputs = new  List<Invoke_UpdateSegmentRevenueClass.FlowInput>();
        Invoke_UpdateSegmentRevenueClass.FlowInput input = new Invoke_UpdateSegmentRevenueClass.FlowInput();
        input.objectName    = 'Supply_Database__c';
        input.dateField     = 'Date__c';
        input.startDate     = Date.valueOf('2024-01-01');
        input.endDate       = Date.valueOf('2024-12-29');
        inputs.add(input);
        Test.startTest();
        Invoke_UpdateSegmentRevenueClass.runBatch(inputs);
        Test.stopTest();
    }
}