Sandbox/07-04-2025/force-app/main/default/objects/Sales_Database__c/Sales_Database__c.object-meta.xml
<CustomObject>
    <label>Sales Database</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Sales Database Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Databases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sandbox/01-02-2025/force-app/main/default/objects/Sales_Database__c/fields/Segment_Category_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Segment_Category_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segment Category Mapping</label>
    <referenceTo>Segment_Category_Mapping__c</referenceTo>
    <relationshipLabel>Sales Databases</relationshipLabel>
    <relationshipName>Sales_Databases</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Sales_Database__c/fields/Segment_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Segment_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segment Mapping</label>
    <referenceTo>Segment_Mapping__c</referenceTo>
    <relationshipLabel>Sales Databases</relationshipLabel>
    <relationshipName>Sales_Databases</relationshipName>
    <type>Lookup</type>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Sales_Database__c/fields/Segment_Name__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name__c</fullName>
    <formula>Segment_Category_Mapping__r.Segment_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Segment Name</label>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Segment_Category_Mapping__c/Segment_Category_Mapping__c.object-meta.xml
<CustomObject>
    <label>Segments Database</label>
    <nameField>
        <displayFormat>SC-{0000000000}</displayFormat>
        <label>Segment Category Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments Database</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Production/01-02-2025/force-app/main/default/objects/Segment_Category_Mapping__c/fields/Segment_Key_Raw__c.field-meta.xml
<CustomField>
    <fullName>Segment_Key_Raw__c</fullName>
    <formula>UPPER( Segment_Code__c )</formula>
    <label>Segment Key Raw</label>
    <type>Text</type>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Segment_Category_Mapping__c/fields/Segment_Name__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name__c</fullName>
    <externalId>true</externalId>
    <label>Segment Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Segment_Mapping__c/Segment_Mapping__c.object-meta.xml
<CustomObject>
    <label>Segment Mapping</label>
    <nameField>
        <displayFormat>SM-{0000000000}</displayFormat>
        <label>Segment Mapping Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segment Mappings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Production/01-02-2025/force-app/main/default/objects/Segment_Mapping__c/fields/Segment_Category_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Segment_Category_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segment Category Mapping</label>
    <referenceTo>Segment_Category_Mapping__c</referenceTo>
    <relationshipName>Segment_Mapping</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Segment_Mapping__c/fields/Segment_Name_Supply_Raw__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name_Supply_Raw__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Please upload SEGMENT KEY in this field (ALL CAPS) for supply data from October 1, 2016 onwards.</inlineHelpText>
    <label>Segment Name (Supply) Raw</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Segment_Monthly_Global__c/Segment_Monthly_Global__c.object-meta.xml
<CustomObject>
    <label>Segment Monthly Global</label>
    <nameField>
        <displayFormat>SMG-{0000000000}</displayFormat>
        <label>Segment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segment Monthly Global</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sandbox/07-04-2025/force-app/main/default/objects/Segment_Monthly_Global__c/fields/Segment_Category_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Segment_Category_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segment Category Mapping</label>
    <referenceTo>Segment_Category_Mapping__c</referenceTo>
    <relationshipLabel>Segment Monthly Global</relationshipLabel>
    <relationshipName>Segment_Monthly_Global</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Segment_Monthly_Global__c/fields/Segment_Key_Raw__c.field-meta.xml
<CustomField>
    <fullName>Segment_Key_Raw__c</fullName>
    <label>Segment Key Raw</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Segment_Monthly_Global__c/fields/Segment_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Segment_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segment Mapping</label>
    <referenceTo>Segment_Mapping__c</referenceTo>
    <relationshipLabel>Segment Monthly Global</relationshipLabel>
    <relationshipName>Segment_Monthly_Global</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Segment_Monthly_Global__c/fields/Segment_Name__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name__c</fullName>
    <formula>Segment_Category_Mapping__r.Segment_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Segment Name</label>
    <type>Text</type>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Segment_Monthly_Global__c/fields/Segment_Name_Supply_Raw__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name_Supply_Raw__c</fullName>
    <label>Segment Name (Supply) Raw</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Segment_Monthly_Global__c/fields/Segment_Name_Supply_Raw_Original__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name_Supply_Raw_Original__c</fullName>
    <label>Segment Name (Supply) Raw Original</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/classes/SegmentMonthlyGlobalTest.cls
@isTest
    public class SegmentMonthlyGlobalTest {
        Static testmethod void SegmentMonthlyGlobalTest(){
            
            Segment_Category_Mapping__c Seg = new Segment_Category_Mapping__c ();
            Seg.Segment_Name__c ='Today';
            insert Seg;
            
            Segment_Mapping__c sm=new Segment_Mapping__c();
            sm.Segment_Category_Mapping__c=seg.Id;
            sm.Segment_Name_Supply_Raw__c='TEST SEGMENT';
            insert sm;
			
            
            
            
            Segment_Category_Mapping__c SegGlobal = new Segment_Category_Mapping__c ();
            SegGlobal.Segment_Name__c = 'India';
            insert SegGlobal;
            
            Segment_Monthly_Global__c smg = new Segment_Monthly_Global__c ();
            
            smg.Segment_Name_Supply_Raw_Original__c='test segment';
            smg.Segment_Name_Supply_Raw__c='TEST SEGMENT';
            smg.Date__c=Date.newInstance(2016, 9, 1);
            smg.Segment_Name_Supply_Raw__c='test raw';
            smg.Segment_Key_Raw__c='test raw';
            smg.Segment_Category_Mapping__c=Seg.Id;
            insert smg;
            smg.Date__c=Date.newInstance(2016, 10, 01);
            smg.Segment_Key_Raw__c='TEST SEGMENT';
            smg.Segment_Name_Supply_Raw__c='TEST SEGMENT';
            update smg;
            
            Sales_Database__c sdb=new Sales_Database__c();
            sdb.Date__c=smg.Date__c;
            sdb.Segment_Category_Mapping__c=Seg.Id;
            insert sdb;
            
                        
            
            
        }
}