Sandbox/07-04-2025/force-app/main/default/objects/Adjustment__c/Adjustment__c.object-meta.xml
<CustomObject>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Adjustment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sandbox/07-04-2025/force-app/main/default/objects/Adjustment__c/fields/Monthly_Rev__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Rev__c</fullName>
    <label>Monthly Rev</label>
    <summarizedField>Adjustment_Transaction__c.Revenue_Amount__c</summarizedField>
    <summaryForeignKey>Adjustment_Transaction__c.Adjustment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Adjustment__c/fields/Total_Monthly_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Total_Monthly_Revenue__c</fullName>
    <formula>Monthly_Rev__c - Monthly_Rev_2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Monthly Earnings</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Adjustment_Type__c/Adjustment_Type__c.object-meta.xml
<CustomObject>
    <label>Adjustment Type</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>Adjustment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustment Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sandbox/07-04-2025/force-app/main/default/objects/Adjustment_Type__c/fields/Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Adjustment__c</fullName>
    <label>Adjustment</label>
    <referenceTo>Adjustment__c</referenceTo>
    <relationshipLabel>Adjustment Types</relationshipLabel>
    <relationshipName>Adjustment_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Adjustment_Type__c/fields/Month_Revenue_Percent__c.field-meta.xml
<CustomField>
    <fullName>Month_Revenue_Percent__c</fullName>
    <formula>( Amount__c /  Adjustment_Monthly_Revenue__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Month Revenue %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Adjustment_Type__c/fields/Remaining_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Adjustment__c</fullName>
    <formula>Amount__c -  Amount_Branded__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Adjustment</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Adjustment_Type__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>33Across</fullName>
            </value>
            <value>
                <fullName>Digital Envoy</fullName>
            </value>
            <value>
                <fullName>ID Graph</fullName>
            </value>
            <value>
                <fullName>ShareThis</fullName>
            </value>
            <value>
                <fullName>TapAd</fullName>
            </value>
            <value>
                <fullName>Tech Cost</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Other 2</fullName>
            </value>
            <value>
                <fullName>Other 1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Supply_Database__c/Supply_Database__c.object-meta.xml
<CustomObject>
    <label>Supply Database</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Supply Database Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supply Databases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sandbox/02-12-2025/force-app/main/default/objects/Supply_Database__c/fields/ComScore_Adjustment_USD__c.field-meta.xml
<CustomField>
    <fullName>ComScore_Adjustment_USD__c</fullName>
    <label>Other Adjustment (USD)</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Supply_Database__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date of the Buy</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Supply_Database__c/fields/Digital_Envoy_Adjustment_USD_NEW__c.field-meta.xml
<CustomField>
    <fullName>Digital_Envoy_Adjustment_USD_NEW__c</fullName>
    <label>Digital Envoy Adjustment (USD) NEW</label>
    <precision>16</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Gross_Earnings_Calc_USD_For_Export__c.field-meta.xml
<CustomField>
    <fullName>Gross_Earnings_Calc_USD_For_Export__c</fullName>
    <formula>Supplier_Gross_Earnings__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gross Earnings Calc USD - For Export</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Supply_Database__c/fields/ID_Graph_Adjustment_USD__c.field-meta.xml
<CustomField>
    <fullName>ID_Graph_Adjustment_USD__c</fullName>
    <label>ID Graph Adjustment (USD)</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Supply_Database__c/fields/ID_Graph_Adjustment_USD_NEW__c.field-meta.xml
<CustomField>
    <fullName>ID_Graph_Adjustment_USD_NEW__c</fullName>
    <label>ID Graph Adjustment (USD) NEW</label>
    <precision>16</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <formula>CASE( 
MONTH( Date__c ), 
1, &quot;January&quot;, 
2, &quot;February&quot;, 
3, &quot;March&quot;, 
4, &quot;April&quot;, 
5, &quot;May&quot;, 
6, &quot;June&quot;, 
7, &quot;July&quot;, 
8, &quot;August&quot;, 
9, &quot;September&quot;, 
10, &quot;October&quot;, 
11, &quot;November&quot;, 
12, &quot;December&quot;, 
&quot;None&quot; 
)+&quot; &quot;+TEXT(YEAR(Date__c))</formula>
    <label>Month</label>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Supply_Database__c/fields/Other_1_Adjustment_USD_NEW__c.field-meta.xml
<CustomField>
    <fullName>Other_1_Adjustment_USD_NEW__c</fullName>
    <label>Other 1 Adjustment (USD) NEW</label>
    <precision>16</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Supply_Database__c/fields/Other_2_Adjustment_USD_NEW__c.field-meta.xml
<CustomField>
    <fullName>Other_2_Adjustment_USD_NEW__c</fullName>
    <label>Other 2 Adjustment (USD) NEW</label>
    <precision>16</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Segment_Supplier_Category__c.field-meta.xml
<CustomField>
    <fullName>Segment_Supplier_Category__c</fullName>
    <formula>Segment_Category_Mapping__r.Segment_Supplier_Category__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Segment Supplier Category</label>
    <type>Text</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Supply_Database__c/fields/ShareThis_Adjustment_USD__c.field-meta.xml
<CustomField>
    <fullName>ShareThis_Adjustment_USD__c</fullName>
    <label>ShareThis Adjustment (USD)</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Supply_Database__c/fields/ShareThis_Adjustment_USD_NEW__c.field-meta.xml
<CustomField>
    <fullName>ShareThis_Adjustment_USD_NEW__c</fullName>
    <label>ShareThis Adjustment (USD) NEW</label>
    <precision>16</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Supplier_Gross_Earnings_Retrospective__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Gross_Earnings_Retrospective__c</fullName>
    <description>For data before 2016 and for Digital Envoy adjustments.</description>
    <label>Digital Envoy Adjustment (USD)</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Supply_Database__c/fields/Supply_Database_Gross_Earnings_Share__c.field-meta.xml
<CustomField>
    <fullName>Supply_Database_Gross_Earnings_Share__c</fullName>
    <label>Supply Database Gross Earnings Share</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Supply_Database__c/fields/TapAd_Adjustment_USD__c.field-meta.xml
<CustomField>
    <fullName>TapAd_Adjustment_USD__c</fullName>
    <label>TapAd Adjustment (USD)</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Supply_Database__c/fields/TapAd_Adjustment_USD_NEW__c.field-meta.xml
<CustomField>
    <fullName>TapAd_Adjustment_USD_NEW__c</fullName>
    <label>TapAd Adjustment (USD) NEW</label>
    <precision>16</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Supply_Database__c/fields/Tech_Cost_Adjustment_USD__c.field-meta.xml
<CustomField>
    <fullName>Tech_Cost_Adjustment_USD__c</fullName>
    <label>Tech Cost Adjustment (USD)</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Tech_Cost_Adjustment_USD_NEW__c.field-meta.xml
<CustomField>
    <fullName>Tech_Cost_Adjustment_USD_NEW__c</fullName>
    <label>Tech Cost Adjustment (USD) NEW</label>
    <precision>16</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Supply_Database__c/fields/X33Across_Adjustment_USD__c.field-meta.xml
<CustomField>
    <fullName>X33Across_Adjustment_USD__c</fullName>
    <label>33Across Adjustment (USD)</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Supply_Database__c/fields/X33Across_Adjustment_USD_NEW__c.field-meta.xml
<CustomField>
    <fullName>X33Across_Adjustment_USD_NEW__c</fullName>
    <defaultValue>0</defaultValue>
    <label>33Across Adjustment (USD) NEW</label>
    <precision>16</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

Sandbox/04-19-2025/force-app/main/default/classes/UpdateSupplyDatabaseBatch.cls
global class UpdateSupplyDatabaseBatch implements Database.Batchable<sObject> {
    public final Adjustment__c adjustment {get; set;}
    public Map<String, Adjustment_Type__c> mapOfAdjustmentTypes {get; set;}
    public final Map<String, Integer> mapOfYears = new Map<String, Integer>{
        'January' => 1,
        'February' => 2,
        'March' => 3,
        'April' => 4,
        'May' => 5,
        'June' => 6,
        'July' => 7,
        'August' => 8,
        'September' => 9,
        'October' => 10,
        'November' => 11,
        'December' => 12
    };
    
    public UpdateSupplyDatabaseBatch(String recordId){
        this.adjustment = [SELECT Id, Year__c, Month__c, Monthly_Rev__c,Total_Monthly_Revenue__c  FROM Adjustment__c WHERE Id =:recordId LIMIT 1];
        this.mapOfAdjustmentTypes = new Map<String, Adjustment_Type__c>();
        List<Adjustment_Type__c> adjustmentTypes = [SELECT Id, Amount__c, Remaining_Adjustment__c, Type__c, Month_Revenue_Percent__c FROM Adjustment_Type__c WHERE Adjustment__c =: adjustment.Id];
        System.debug('adjustmentTypes adjustmentTypes adjustmentTypes' + adjustmentTypes);
        if( adjustmentTypes.size() > 0 ){
            for(Adjustment_Type__c adjustmentType : adjustmentTypes){
                this.mapOfAdjustmentTypes.put(adjustmentType.Type__c, adjustmentType);
            }
        }
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        Integer year            = Integer.valueOf(adjustment.Year__c);
        Integer month           = mapOfYears.get(adjustment.Month__c);
        Integer lastDay         = Date.daysInMonth(year, month);
        Date firstDayOfMonth    = Date.newInstance(year, month, 1);
        Date lastDayOfMonth     = Date.newInstance(year, month, lastDay);
        
        String query = 'SELECT Id, Gross_Earnings_Calc_USD_For_Export__c, Supply_Database_Gross_Earnings_Share__c, Segment_Supplier_Category__c FROM Supply_Database__c WHERE Date__c >= :firstDayOfMonth AND Date__c <= :lastDayOfMonth';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<Supply_Database__c> records){
        System.debug('mapOfAdjustmentTypes mapOfAdjustmentTypes mapOfAdjustmentTypes' + mapOfAdjustmentTypes);
        for(Supply_Database__c record : records){

            //Double monthlyEarningsPercentage = (record.Gross_Earnings_Calc_USD_For_Export__c / adjustment.Monthly_Rev__c);
            Double monthlyEarningsPercentage = (record.Gross_Earnings_Calc_USD_For_Export__c / adjustment.Total_Monthly_Revenue__c); 
            Double newCalculation = (record.Gross_Earnings_Calc_USD_For_Export__c * 0.02);

            record.Supply_Database_Gross_Earnings_Share__c =  monthlyEarningsPercentage;
            if(mapOfAdjustmentTypes.containsKey('33Across')){
                // record.X33Across_Adjustment_USD__c = mapOfAdjustmentTypes.get('33Across').Amount__c * monthlyEarningsPercentage;
                if(record.Segment_Supplier_Category__c == 'Branded'){
                    record.X33Across_Adjustment_USD_NEW__c = (mapOfAdjustmentTypes.get('33Across').Month_Revenue_Percent__c / 100) * newCalculation * -1;
                } else {
                    record.X33Across_Adjustment_USD_NEW__c = (mapOfAdjustmentTypes.get('33Across').Remaining_Adjustment__c * monthlyEarningsPercentage) * -1;
                }
            }

            if(mapOfAdjustmentTypes.containsKey('Digital Envoy')){
                // record.Supplier_Gross_Earnings_Retrospective__c  = mapOfAdjustmentTypes.get('Digital Envoy').Amount__c * monthlyEarningsPercentage;
                if(record.Segment_Supplier_Category__c == 'Branded'){
                    record.Digital_Envoy_Adjustment_USD_NEW__c  = (mapOfAdjustmentTypes.get('Digital Envoy').Month_Revenue_Percent__c / 100) * newCalculation * -1;
                } else {
                    record.Digital_Envoy_Adjustment_USD_NEW__c  = (mapOfAdjustmentTypes.get('Digital Envoy').Remaining_Adjustment__c * monthlyEarningsPercentage) * -1;
                }
            }
            
            if(mapOfAdjustmentTypes.containsKey('ID Graph')){
                // record.ID_Graph_Adjustment_USD__c = mapOfAdjustmentTypes.get('ID Graph').Amount__c * monthlyEarningsPercentage;
                if(record.Segment_Supplier_Category__c == 'Branded'){
                    record.ID_Graph_Adjustment_USD_NEW__c = (mapOfAdjustmentTypes.get('ID Graph').Month_Revenue_Percent__c / 100) * newCalculation * -1;
                } else {
                    record.ID_Graph_Adjustment_USD_NEW__c  = (mapOfAdjustmentTypes.get('ID Graph').Remaining_Adjustment__c * monthlyEarningsPercentage) * -1;
                }
            }

            if(mapOfAdjustmentTypes.containsKey('ShareThis')){
                // record.ShareThis_Adjustment_USD__c = mapOfAdjustmentTypes.get('ShareThis').Amount__c * monthlyEarningsPercentage;
                if(record.Segment_Supplier_Category__c == 'Branded'){
                    record.ShareThis_Adjustment_USD_NEW__c = (mapOfAdjustmentTypes.get('ShareThis').Month_Revenue_Percent__c / 100) * newCalculation * -1;
                } else {
                    record.ShareThis_Adjustment_USD_NEW__c  = (mapOfAdjustmentTypes.get('ShareThis').Remaining_Adjustment__c * monthlyEarningsPercentage) * -1;
                }
            }

            if(mapOfAdjustmentTypes.containsKey('TapAd')){
                // record.TapAd_Adjustment_USD__c = mapOfAdjustmentTypes.get('TapAd').Amount__c * monthlyEarningsPercentage;
                if(record.Segment_Supplier_Category__c == 'Branded'){
                    record.TapAd_Adjustment_USD_NEW__c = (mapOfAdjustmentTypes.get('TapAd').Month_Revenue_Percent__c / 100) * newCalculation * -1;
                } else {
                    record.TapAd_Adjustment_USD_NEW__c  = (mapOfAdjustmentTypes.get('TapAd').Remaining_Adjustment__c * monthlyEarningsPercentage) * -1;
                }
            }

            if(mapOfAdjustmentTypes.containsKey('Tech Cost')){
                // record.Tech_Cost_Adjustment_USD__c = mapOfAdjustmentTypes.get('Tech Cost').Amount__c * monthlyEarningsPercentage;
                if(record.Segment_Supplier_Category__c == 'Branded'){
                    record.Tech_Cost_Adjustment_USD_NEW__c = (mapOfAdjustmentTypes.get('Tech Cost').Month_Revenue_Percent__c / 100) * newCalculation * -1;
                } else {
                    record.Tech_Cost_Adjustment_USD_NEW__c  = (mapOfAdjustmentTypes.get('Tech Cost').Remaining_Adjustment__c * monthlyEarningsPercentage) * -1;
                }
            }

            // if(mapOfAdjustmentTypes.containsKey('Other')){
            //     record.ComScore_Adjustment_USD__c = mapOfAdjustmentTypes.get('Other').Amount__c * monthlyEarningsPercentage;
            // }

            if(mapOfAdjustmentTypes.containsKey('Other 1')){
                if(record.Segment_Supplier_Category__c == 'Branded'){
                    record.Other_1_Adjustment_USD_NEW__c = (mapOfAdjustmentTypes.get('Other 1').Month_Revenue_Percent__c / 100) * newCalculation * -1;
                } else {
                    record.Other_1_Adjustment_USD_NEW__c  = (mapOfAdjustmentTypes.get('Other 1').Remaining_Adjustment__c * monthlyEarningsPercentage) * -1;
                }
            }

            if(mapOfAdjustmentTypes.containsKey('Other 2')){
                if(record.Segment_Supplier_Category__c == 'Branded'){
                    record.Other_2_Adjustment_USD_NEW__c = (mapOfAdjustmentTypes.get('Other 2').Month_Revenue_Percent__c / 100) * newCalculation * -1;
                } else {
                    record.Other_2_Adjustment_USD_NEW__c  = (mapOfAdjustmentTypes.get('Other 2').Remaining_Adjustment__c * monthlyEarningsPercentage) * -1;
                }
            }
        }
        
        System.debug('records records records' + records);
        update records;
    }   

    global void finish(Database.BatchableContext bc){
        //Finish
    }    
}