Sandbox/07-04-2025/force-app/main/default/objects/Adjustment__c/Adjustment__c.object-meta.xml
<CustomObject>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Adjustment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sandbox/07-02-2025/force-app/main/default/objects/Adjustment_Type__c/Adjustment_Type__c.object-meta.xml
<CustomObject>
    <label>Adjustment Type</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>Adjustment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustment Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sandbox/07-04-2025/force-app/main/default/objects/Adjustment_Type__c/fields/Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Adjustment__c</fullName>
    <label>Adjustment</label>
    <referenceTo>Adjustment__c</referenceTo>
    <relationshipLabel>Adjustment Types</relationshipLabel>
    <relationshipName>Adjustment_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Adjustment_Type__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>33Across</fullName>
            </value>
            <value>
                <fullName>Digital Envoy</fullName>
            </value>
            <value>
                <fullName>ID Graph</fullName>
            </value>
            <value>
                <fullName>ShareThis</fullName>
            </value>
            <value>
                <fullName>TapAd</fullName>
            </value>
            <value>
                <fullName>Tech Cost</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Other 2</fullName>
            </value>
            <value>
                <fullName>Other 1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/classes/AdjustmentController.cls
public with sharing class AdjustmentController {
    public static void createAdjustment(){
        DateTime today = System.now().addMonths(1);

        Adjustment__c adjustment = new Adjustment__c(
            Month__c = today.format('MMMM'),
            Year__c = String.valueOf(today.year())
        );
        
        insert adjustment;
    }

    @AuraEnabled
    public static string createAdjustmentAndTypes(String month, String year){
        try {
            List<Adjustment__c> adjustments = [SELECT Id, (SELECT Amount__c, Type__c, CurrencyIsoCode FROM Adjustment_Types__r) FROM Adjustment__c ORDER BY CreatedDate DESC LIMIT 1];

            Adjustment__c newAdjustment = new Adjustment__c(
                Month__c = month,
                Year__c = year
            );
            
            insert newAdjustment;

            List<Adjustment_Type__c> adjustmentTypes = new List<Adjustment_Type__c>();

            System.debug( 'adjustments adjustments' + adjustments);


            if(adjustments.size() > 0){
                for(Adjustment__c adjustment : adjustments){
                    System.debug( 'adjustmentadjustment.Adjustment_Types__r' + adjustment.Adjustment_Types__r);
                    if(adjustment.Adjustment_Types__r.size() > 0 ){
                        for( Adjustment_Type__c adjustmentType : adjustment.Adjustment_Types__r ){

                            Adjustment_Type__c newAdjustmentType  = adjustmentType.clone(false, false, false, false);
                            newAdjustmentType.Adjustment__c = newAdjustment.Id;

                            System.debug( 'newAdjustmentType newAdjustmentType' + newAdjustmentType);

                            adjustmentTypes.add(newAdjustmentType);
                        }
                    }
                }
            }

            System.debug('adjustmentTypes adjustmentTypes adjustmentTypes' + adjustmentTypes);

            if(adjustmentTypes.size() > 0){
                insert adjustmentTypes;
            }

            return newAdjustment.Id;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}