Sandbox/07-04-2025/force-app/main/default/objects/Adjustment__c/Adjustment__c.object-meta.xml
<CustomObject>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Adjustment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sandbox/07-04-2025/force-app/main/default/objects/Adjustment__c/fields/Monthly_Rev__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Rev__c</fullName>
    <label>Monthly Rev</label>
    <summarizedField>Adjustment_Transaction__c.Revenue_Amount__c</summarizedField>
    <summaryForeignKey>Adjustment_Transaction__c.Adjustment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Segment_Revenue_Transaction__c/Segment_Revenue_Transaction__c.object-meta.xml
<CustomObject>
    <description>Join Object between Sales and Supply Databases.</description>
    <label>Segment Revenue Transaction</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>Segment Transactions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segment Revenue Transactions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sandbox/07-02-2025/force-app/main/default/objects/Segment_Revenue_Transaction__c/fields/Total_Adjustments__c.field-meta.xml
<CustomField>
    <fullName>Total_Adjustments__c</fullName>
    <label>Total Adjustments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Segment_Revenue_Transaction__c/fields/Total_Adjustments_NEW__c.field-meta.xml
<CustomField>
    <fullName>Total_Adjustments_NEW__c</fullName>
    <label>Total Adjustments NEW</label>
    <precision>16</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Supply_Database__c/Supply_Database__c.object-meta.xml
<CustomObject>
    <label>Supply Database</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Supply Database Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supply Databases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sandbox/02-12-2025/force-app/main/default/objects/Supply_Database__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date of the Buy</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <formula>CASE( 
MONTH( Date__c ), 
1, &quot;January&quot;, 
2, &quot;February&quot;, 
3, &quot;March&quot;, 
4, &quot;April&quot;, 
5, &quot;May&quot;, 
6, &quot;June&quot;, 
7, &quot;July&quot;, 
8, &quot;August&quot;, 
9, &quot;September&quot;, 
10, &quot;October&quot;, 
11, &quot;November&quot;, 
12, &quot;December&quot;, 
&quot;None&quot; 
)+&quot; &quot;+TEXT(YEAR(Date__c))</formula>
    <label>Month</label>
    <type>Text</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Supply_Database__c/fields/Segment_Revenue_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Segment_Revenue_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Join to Segment Revenue Transaction Object</description>
    <inlineHelpText>Join to Segment Revenue Transaction Object</inlineHelpText>
    <label>Segment Revenue Transaction</label>
    <referenceTo>Segment_Revenue_Transaction__c</referenceTo>
    <relationshipLabel>Supply Databases</relationshipLabel>
    <relationshipName>Supply_Databases</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Total_Adjustments__c.field-meta.xml
<CustomField>
    <fullName>Total_Adjustments__c</fullName>
    <formula>X33Across_Adjustment_USD__c + Supplier_Gross_Earnings_Retrospective__c + ID_Graph_Adjustment_USD__c + ShareThis_Adjustment_USD__c + TapAd_Adjustment_USD__c + Tech_Cost_Adjustment_USD__c + ComScore_Adjustment_USD__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Adjustments</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Currency</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Total_Adjustments_NEW__c.field-meta.xml
<CustomField>
    <fullName>Total_Adjustments_NEW__c</fullName>
    <formula>X33Across_Adjustment_USD_NEW__c + Digital_Envoy_Adjustment_USD_NEW__c + ID_Graph_Adjustment_USD_NEW__c + ShareThis_Adjustment_USD_NEW__c + TapAd_Adjustment_USD_NEW__c + Tech_Cost_Adjustment_USD_NEW__c + Other_1_Adjustment_USD_NEW__c + Other_2_Adjustment_USD_NEW__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Adjustments NEW</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Sandbox/04-19-2025/force-app/main/default/classes/UpdateSegmentTotalAdjustment.cls
global with sharing class UpdateSegmentTotalAdjustment implements Database.Batchable<sObject> {
    public final Adjustment__c adjustment {get; set;}
    public final Map<String, Integer> mapOfYears = new Map<String, Integer>{
        'January' => 1,
        'February' => 2,
        'March' => 3,
        'April' => 4,
        'May' => 5,
        'June' => 6,
        'July' => 7,
        'August' => 8,
        'September' => 9,
        'October' => 10,
        'November' => 11,
        'December' => 12
    };

    public UpdateSegmentTotalAdjustment(String recordId){
       this.adjustment = [SELECT Id, Year__c, Month__c, Monthly_Rev__c FROM Adjustment__c WHERE Id =:recordId LIMIT 1];
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        Integer year            = Integer.valueOf(adjustment.Year__c);
        Integer month           = mapOfYears.get(adjustment.Month__c);
        Integer lastDay         = Date.daysInMonth(year, month);
        Date firstDayOfMonth    = Date.newInstance(year, month, 1);
        Date lastDayOfMonth     = Date.newInstance(year, month, lastDay);

        String query = 'SELECT Id, Segment_Revenue_Transaction__c FROM Supply_Database__c WHERE Date__c >= :firstDayOfMonth AND Date__c <= :lastDayOfMonth';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<Supply_Database__c> records){

        System.debug('records' + records);

        Set<Id> segmentRevenueTransactionIds = new Set<Id>();
        for(Supply_Database__c record : records){
            segmentRevenueTransactionIds.add(record.Segment_Revenue_Transaction__c);
        }

        List<AggregateResult> results =  [SELECT Segment_Revenue_Transaction__c, SUM(Total_Adjustments__c) totalAdjustments, SUM(Total_Adjustments_NEW__c) totalAdjustmentsNew FROM Supply_Database__c WHERE Segment_Revenue_Transaction__c IN :segmentRevenueTransactionIds GROUP BY Segment_Revenue_Transaction__c];

        if(results.size() > 0){
            List<Segment_Revenue_Transaction__c> segments = new List<Segment_Revenue_Transaction__c>();
            for (AggregateResult result : results){
                Segment_Revenue_Transaction__c segment = new Segment_Revenue_Transaction__c(
                    Id = (Id) result.get('Segment_Revenue_Transaction__c'),
                    Total_Adjustments__c = (Double) result.get('totalAdjustments'),
                    Total_Adjustments_NEW__c = (Double) result.get('totalAdjustmentsNew')
                    //Total_Adjustments_NEW__c = (-1 * (Double) result.get('totalAdjustmentsNew'))
                );
                segments.add(segment);
            }
    
            System.debug('segments segments segments' + segments);
    
            if( segments.size() > 0 ){  
                update segments;
            }
        }
    }   

    global void finish(Database.BatchableContext bc){
        //Finish
    }    
}