Sandbox/07-04-2025/force-app/main/default/objects/Adjustment__c/Adjustment__c.object-meta.xml
<CustomObject>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Adjustment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sandbox/07-04-2025/force-app/main/default/objects/Adjustment__c/fields/Monthly_Rev__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Rev__c</fullName>
    <label>Monthly Rev</label>
    <summarizedField>Adjustment_Transaction__c.Revenue_Amount__c</summarizedField>
    <summaryForeignKey>Adjustment_Transaction__c.Adjustment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Adjustment_Transaction__c/Adjustment_Transaction__c.object-meta.xml
<CustomObject>
    <label>Adjustment Transaction</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>Adjustment Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustment Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Production/01-02-2025/force-app/main/default/objects/Adjustment_Transaction__c/fields/Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Adjustment__c</fullName>
    <label>Adjustment</label>
    <referenceTo>Adjustment__c</referenceTo>
    <relationshipLabel>Adjustment Transactions</relationshipLabel>
    <relationshipName>Adjustment_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Adjustment_Transaction__c/fields/Branded_Adjustment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Branded_Adjustment_Amount__c</fullName>
    <label>Branded Adjustment Amount</label>
    <precision>16</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Adjustment_Transaction__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Adjustment_Transaction__c/fields/Revenue_Amount__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Amount__c</fullName>
    <label>Revenue Amount</label>
    <precision>16</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Adjustment_Transaction__c/fields/Segment_Category__c.field-meta.xml
<CustomField>
    <fullName>Segment_Category__c</fullName>
    <label>Segment Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Adjustment_Transaction__c/fields/Supply_Database__c.field-meta.xml
<CustomField>
    <fullName>Supply_Database__c</fullName>
    <label>Supply Database</label>
    <referenceTo>Supply_Database__c</referenceTo>
    <relationshipLabel>Adjustment Transactions</relationshipLabel>
    <relationshipName>Adjustment_Transactions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Supply_Database__c/Supply_Database__c.object-meta.xml
<CustomObject>
    <label>Supply Database</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Supply Database Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supply Databases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sandbox/07-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Branded_Adjustment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Branded_Adjustment_Amount__c</fullName>
    <formula>Gross_Earnings_Calc_USD_For_Export__c * 0.02</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branded Adjustment Amount</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Supply_Database__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date of the Buy</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Gross_Earnings_Calc_USD_For_Export__c.field-meta.xml
<CustomField>
    <fullName>Gross_Earnings_Calc_USD_For_Export__c</fullName>
    <formula>Supplier_Gross_Earnings__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gross Earnings Calc USD - For Export</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <formula>CASE( 
MONTH( Date__c ), 
1, &quot;January&quot;, 
2, &quot;February&quot;, 
3, &quot;March&quot;, 
4, &quot;April&quot;, 
5, &quot;May&quot;, 
6, &quot;June&quot;, 
7, &quot;July&quot;, 
8, &quot;August&quot;, 
9, &quot;September&quot;, 
10, &quot;October&quot;, 
11, &quot;November&quot;, 
12, &quot;December&quot;, 
&quot;None&quot; 
)+&quot; &quot;+TEXT(YEAR(Date__c))</formula>
    <label>Month</label>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Supply_Database__c/fields/Segment_Category__c.field-meta.xml
<CustomField>
    <fullName>Segment_Category__c</fullName>
    <formula>TEXT(Segment_Category_Mapping__r.Segment_Category_NEW_2018__c)</formula>
    <label>Segment Category</label>
    <type>Text</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Segment_Supplier_Category__c.field-meta.xml
<CustomField>
    <fullName>Segment_Supplier_Category__c</fullName>
    <formula>Segment_Category_Mapping__r.Segment_Supplier_Category__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Segment Supplier Category</label>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/classes/AdjTransactionCreationBatch.cls
global class AdjTransactionCreationBatch implements Database.Batchable<sObject> {
    public final Adjustment__c adjustment {get; set;}
    public final Map<String, Integer> mapOfYears = new Map<String, Integer>{
        'January' => 1,
        'February' => 2,
        'March' => 3,
        'April' => 4,
        'May' => 5,
        'June' => 6,
        'July' => 7,
        'August' => 8,
        'September' => 9,
        'October' => 10,
        'November' => 11,
        'December' => 12
    };

    public AdjTransactionCreationBatch(String recordId){
        System.debug('recordId' + recordId);
        this.adjustment = [SELECT Id, Year__c, Month__c, Monthly_Rev__c FROM Adjustment__c WHERE Id =:recordId LIMIT 1];
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        System.debug(' this.adjustment' +  adjustment);
        Integer year            = Integer.valueOf(adjustment.Year__c);
        Integer month           = mapOfYears.get(adjustment.Month__c);

        System.debug('year year' + year);
        System.debug('month month' + month);

        Integer lastDay         = Date.daysInMonth(year, month);
        Date firstDayOfMonth    = Date.newInstance(year, month, 1);
        Date secondDayOfMonth    = Date.newInstance(year, month, 2);
        Date lastDayOfMonth     = Date.newInstance(year, month, lastDay);
        
        //old query
        //String query = 'SELECT Id, Gross_Earnings_Calc_USD_For_Export__c, Branded_Adjustment_Amount__c,Segment_Supplier_Category__c FROM Supply_Database__c WHERE Date__c >= :firstDayOfMonth AND Date__c <= :lastDayOfMonth';
        String query = 'SELECT Id, Gross_Earnings_Calc_USD_For_Export__c, Branded_Adjustment_Amount__c,Segment_Supplier_Category__c FROM Supply_Database__c WHERE Date__c >= :firstDayOfMonth AND Date__c <= :secondDayOfMonth';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<Supply_Database__c> records){
        
        if(records.size() > 0){
            List<Adjustment_Transaction__c> adjustmentTransactions = new List<Adjustment_Transaction__c>();
            
            for( Supply_Database__c record : records ){
                                
                Adjustment_Transaction__c adjustmentTransaction = new Adjustment_Transaction__c(
                    Supply_Database__c = record.Id,
                    Year__c = adjustment.Year__c,
                    Month__c = adjustment.Month__c,
                    Adjustment__c = adjustment.Id,
                    Revenue_Amount__c = record.Gross_Earnings_Calc_USD_For_Export__c,
                    //Revenue_Amount__c = (record.Segment_Supplier_Category__c != 'Branded') ?  record.Gross_Earnings_Calc_USD_For_Export__c: 0,
                    Segment_Category__c = record.Segment_Supplier_Category__c,
                    //Branded_Adjustment_Amount__c = record.Branded_Adjustment_Amount__c
                    Branded_Adjustment_Amount__c = (record.Segment_Supplier_Category__c == 'Branded') ?  record.Branded_Adjustment_Amount__c: 0
                );
                
                adjustmentTransactions.add(adjustmentTransaction);
            }
            
            System.debug('adjustmentTransactions adjustmentTransactions adjustmentTransactions' + adjustmentTransactions);
            
            if( adjustmentTransactions.size() > 0 ){
                try {
                    insert adjustmentTransactions;
                } catch(DmlException e) {
                    System.debug('The following exception has occurred: ' + e.getMessage());
                }
            }
        }
        
    }   
    
    global void finish(Database.BatchableContext bc){
        //Finish
    }    
}