Sandbox/07-02-2025/force-app/main/default/objects/Audience_Report__c/Audience_Report__c.object-meta.xml
<CustomObject>
    <label>Audience Report</label>
    <nameField>
        <displayFormat>AR-{YY}-{MM}-{0000}</displayFormat>
        <label>Audience Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audience Report</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sandbox/07-02-2025/force-app/main/default/objects/Audience_Report__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Audience Report</relationshipLabel>
    <relationshipName>Audience_Report</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Audience_Report__c/fields/Country_Raw__c.field-meta.xml
<CustomField>
    <fullName>Country_Raw__c</fullName>
    <label>Country Raw</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Audience_Report__c/fields/Data_Supplier_Raw_Original__c.field-meta.xml
<CustomField>
    <fullName>Data_Supplier_Raw_Original__c</fullName>
    <label>Data Supplier Raw Original</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Audience_Report__c/fields/Keywords__c.field-meta.xml
<CustomField>
    <fullName>Keywords__c</fullName>
    <label>Keywords</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Audience_Report__c/fields/Segment_Key__c.field-meta.xml
<CustomField>
    <fullName>Segment_Key__c</fullName>
    <label>Segment Key</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Audience_Report__c/fields/Segment_Name__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segment Category Mapping</label>
    <referenceTo>Segment_Category_Mapping__c</referenceTo>
    <relationshipLabel>Audience Report</relationshipLabel>
    <relationshipName>Audience_Report</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sandbox/02-12-2025/force-app/main/default/objects/Country__c/fields/Master_Geography_Code__c.field-meta.xml
<CustomField>
    <fullName>Master_Geography_Code__c</fullName>
    <label>Master Geography Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Data_Supplier_Mapping__c/Data_Supplier_Mapping__c.object-meta.xml
<CustomObject>
    <label>Data Supplier Mapping</label>
    <nameField>
        <displayFormat>DSM-{0000000000}</displayFormat>
        <label>Data Supplier Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Supplier Mappings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sandbox/01-02-2025/force-app/main/default/objects/Data_Supplier_Mapping__c/fields/Data_Supplier_Account__c.field-meta.xml
<CustomField>
    <fullName>Data_Supplier_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Data Supplier Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Data Supplier Mappings</relationshipLabel>
    <relationshipName>Data_Supplier_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Data_Supplier_Mapping__c/fields/Data_Supplier_Raw__c.field-meta.xml
<CustomField>
    <fullName>Data_Supplier_Raw__c</fullName>
    <label>Data Supplier Raw</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Segment_Category_Mapping__c/Segment_Category_Mapping__c.object-meta.xml
<CustomObject>
    <label>Segments Database</label>
    <nameField>
        <displayFormat>SC-{0000000000}</displayFormat>
        <label>Segment Category Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments Database</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sandbox/01-02-2025/force-app/main/default/objects/Segment_Category_Mapping__c/fields/Segment_Code__c.field-meta.xml
<CustomField>
    <fullName>Segment_Code__c</fullName>
    <label>Segment Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Segment_Category_Mapping__c/fields/Segment_Description__c.field-meta.xml
<CustomField>
    <fullName>Segment_Description__c</fullName>
    <label>Segment Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Segment_Category_Mapping__c/fields/Segment_Name__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name__c</fullName>
    <externalId>true</externalId>
    <label>Segment Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Production/04-19-2025/force-app/main/default/classes/AudienceReportTest.cls
@isTest
private class AudienceReportTest {
static testMethod void AudienceReportTest() {
 
        
        //create Country Mapping Record for mapping
        Country__c Country = new Country__c(Master_Geography_Code__c='TEST', Name='Test Country');
        Insert Country;
        
        
        // create Segment Category Mapping Record for mapping
        Segment_Category_Mapping__c SegCatMap = new Segment_Category_Mapping__c(Segment_Name__c='Test Segment', Segment_Code__c='Test Segment Key', Segment_Description__c='Test Description', Keywords__c='Test Keywords');
        Insert SegCatMap;
        
        //create Data Supplier Account for mapping
        Account Acc = new Account (Name='Test Account');
        Insert Acc;
        
        //create Data Supplier Mapping Record for mapping
        Data_Supplier_Mapping__c DataSupMap = new Data_Supplier_Mapping__c(Data_Supplier_Raw__c='TEST RAW DATA SUPPLIER', Data_Supplier_Account__c=Acc.id);
        Insert DataSupMap;


        // add Audience Report entries to be inserted
        Audience_Report__c AR = new Audience_Report__c (Data_Supplier_Raw_Original__c='Test Raw Data Supplier', Segment_Key__c='Test Segment Key', Country_Raw__c='TEST');
        Insert AR;
        Audience_Report__c ARExceptions = new Audience_Report__c (Data_Supplier_Raw_Original__c='Test Raw Data Supplier Error', Segment_Key__c='Test Segment Key Error', Country_Raw__c='TEST ERROR');
        Insert ARExceptions;

       }
    }