Sandbox/07-02-2025/force-app/main/default/objects/Audience_Report__c/Audience_Report__c.object-meta.xml
<CustomObject>
    <label>Audience Report</label>
    <nameField>
        <displayFormat>AR-{YY}-{MM}-{0000}</displayFormat>
        <label>Audience Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audience Report</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sandbox/07-02-2025/force-app/main/default/objects/Audience_Report__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Audience Report</relationshipLabel>
    <relationshipName>Audience_Report</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Audience_Report__c/fields/Country_Error__c.field-meta.xml
<CustomField>
    <fullName>Country_Error__c</fullName>
    <label>Country Error</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Audience_Report__c/fields/Country_Raw__c.field-meta.xml
<CustomField>
    <fullName>Country_Raw__c</fullName>
    <label>Country Raw</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Audience_Report__c/fields/Data_Supplier__c.field-meta.xml
<CustomField>
    <fullName>Data_Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Data Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Audience Report</relationshipLabel>
    <relationshipName>Audience_Report</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Audience_Report__c/fields/Data_Supplier_Error__c.field-meta.xml
<CustomField>
    <fullName>Data_Supplier_Error__c</fullName>
    <label>Data Supplier Error</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Audience_Report__c/fields/Data_Supplier_Raw_Original__c.field-meta.xml
<CustomField>
    <fullName>Data_Supplier_Raw_Original__c</fullName>
    <label>Data Supplier Raw Original</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Audience_Report__c/fields/Data_Supplier_RAW_UPPER__c.field-meta.xml
<CustomField>
    <fullName>Data_Supplier_RAW_UPPER__c</fullName>
    <label>Data Supplier Raw</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Audience_Report__c/fields/Keywords__c.field-meta.xml
<CustomField>
    <fullName>Keywords__c</fullName>
    <label>Keywords</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Audience_Report__c/fields/Segment_Error__c.field-meta.xml
<CustomField>
    <fullName>Segment_Error__c</fullName>
    <label>Segment Error</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Audience_Report__c/fields/Segment_Key__c.field-meta.xml
<CustomField>
    <fullName>Segment_Key__c</fullName>
    <label>Segment Key</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Audience_Report__c/fields/Segment_Name__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segment Category Mapping</label>
    <referenceTo>Segment_Category_Mapping__c</referenceTo>
    <relationshipLabel>Audience Report</relationshipLabel>
    <relationshipName>Audience_Report</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sandbox/02-12-2025/force-app/main/default/objects/Country__c/fields/Master_Geography_Code__c.field-meta.xml
<CustomField>
    <fullName>Master_Geography_Code__c</fullName>
    <label>Master Geography Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Data_Supplier_Mapping__c/Data_Supplier_Mapping__c.object-meta.xml
<CustomObject>
    <label>Data Supplier Mapping</label>
    <nameField>
        <displayFormat>DSM-{0000000000}</displayFormat>
        <label>Data Supplier Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Supplier Mappings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sandbox/07-02-2025/force-app/main/default/objects/Data_Supplier_Mapping__c/fields/Data_Supplier__c.field-meta.xml
<CustomField>
    <fullName>Data_Supplier__c</fullName>
    <formula>Data_Supplier_Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Data Supplier</label>
    <type>Text</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Data_Supplier_Mapping__c/fields/Data_Supplier_Account__c.field-meta.xml
<CustomField>
    <fullName>Data_Supplier_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Data Supplier Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Data Supplier Mappings</relationshipLabel>
    <relationshipName>Data_Supplier_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Data_Supplier_Mapping__c/fields/Data_Supplier_Raw__c.field-meta.xml
<CustomField>
    <fullName>Data_Supplier_Raw__c</fullName>
    <label>Data Supplier Raw</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Segment_Category_Mapping__c/Segment_Category_Mapping__c.object-meta.xml
<CustomObject>
    <label>Segments Database</label>
    <nameField>
        <displayFormat>SC-{0000000000}</displayFormat>
        <label>Segment Category Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments Database</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Production/01-02-2025/force-app/main/default/objects/Segment_Category_Mapping__c/fields/Data_Supplier__c.field-meta.xml
<CustomField>
    <fullName>Data_Supplier__c</fullName>
    <formula>Data_Asset_Account__r.Parent.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Data Supplier</label>
    <type>Text</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Segment_Category_Mapping__c/fields/Segment_Code__c.field-meta.xml
<CustomField>
    <fullName>Segment_Code__c</fullName>
    <label>Segment Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Segment_Category_Mapping__c/fields/Segment_Description__c.field-meta.xml
<CustomField>
    <fullName>Segment_Description__c</fullName>
    <label>Segment Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Segment_Category_Mapping__c/fields/Segment_Name__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name__c</fullName>
    <externalId>true</externalId>
    <label>Segment Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/04-19-2025/force-app/main/default/classes/AudienceReportTriggerHandler.cls
public class AudienceReportTriggerHandler {

    public static void onBeforeInsertUpdate(List<Audience_Report__c> audienceReportList) {

        //Create Sets of all values to be mapped
        Set<String> SegmentKeys = new Set<String>();
        Set<String> Countries = new Set<String>();
        Set<String> DataSupplierRaw = new Set<String>();

        //Create Lists of all mapping keys
        Map<String,Segment_Category_Mapping__c> mastersheet = new Map<String,Segment_Category_Mapping__c>();
        Map<String,Country__c> mastercountries = new Map<String,Country__c>();
        Map<String,Data_Supplier_Mapping__c> masterdatasuppliers = new Map<String,Data_Supplier_Mapping__c>();

        for(Audience_Report__c audiencereport : audienceReportList) {
            if(audiencereport.Segment_Key__c != ''){
                SegmentKeys.add(audiencereport.Segment_Key__c);
            }
            if(audiencereport.Country_Raw__c != ''){
                Countries.add(audiencereport.Country_Raw__c);
            }
            if(audiencereport.Data_Supplier_Raw_Original__c != ''){
                audiencereport.Data_Supplier_RAW_UPPER__c = audiencereport.Data_Supplier_Raw_Original__c.toUpperCase().trim();
                DataSupplierRaw.add(audiencereport.Data_Supplier_RAW_UPPER__c);
            }
        }

        for(Segment_Category_Mapping__c objSegmentCM : [Select Id, 
                                                                Segment_Name__c, 
                                                                Segment_Code__c, 
                                                                Segment_Description__c, 
                                                                Keywords__c FROM Segment_Category_Mapping__c 
                                                                WHERE Segment_Code__c IN :SegmentKeys]){
            mastersheet.put(objSegmentCM.Segment_Code__c, objSegmentCM);
        }

        for(Country__c objCountry : [Select Id, 
                                            Master_Geography_Code__c, 
                                            Name FROM Country__c 
                                            WHERE Master_Geography_Code__c IN :Countries]) {
            mastercountries.put(objCountry.Master_Geography_Code__c,objCountry);
        }

        for(Data_Supplier_Mapping__c objdatasuppliermappings : [Select Id, 
                                                                        Data_Supplier_Account__c,
                                                                        Data_Supplier_Raw__c FROM Data_Supplier_Mapping__c 
                                                                        WHERE Data_Supplier_Raw__c IN : DataSupplierRaw]) {
            masterdatasuppliers.put(objdatasuppliermappings.Data_Supplier_Raw__c, objdatasuppliermappings);
        }

        for(Audience_Report__c audiencereport : audienceReportList) {
            
            if(audiencereport.Segment_Key__c!=null && audiencereport.Segment_Key__c!= '' && 
            (!mastersheet.isEmpty() && mastersheet.containsKey(audiencereport.Segment_Key__c))) {
                audiencereport.Segment_Name__c = mastersheet.get(audiencereport.Segment_Key__c)?.Id;
                audiencereport.Segment_Description__c = mastersheet.get(audiencereport.Segment_Key__c)?.Segment_Description__c;
                audiencereport.Keywords__c = mastersheet.get(audiencereport.Segment_Key__c)?.Keywords__c;
                audiencereport.Segment_Error__c = null;
            }
            else {
                audiencereport.Segment_Error__c = 'Error: Segment Category Mapping not found.';
                audiencereport.Segment_Name__c = null;
                audiencereport.Segment_Description__c = null;
                audiencereport.Keywords__c = null;
            }

            if (audiencereport.Country_Raw__c != null && audiencereport.Country_Raw__c != '' && 
                (!mastercountries.isEmpty() && mastercountries.containsKey(audiencereport.Country_Raw__c))) {
                    audiencereport.Country__c = mastercountries.get(audiencereport.Country_Raw__c)?.Id;
                    audiencereport.Country_Error__c = null;
            }
            else {
                audiencereport.Country_Error__c = 'Error: Country mapping not found.';
                audiencereport.Country__c = null;
            }

            if(audiencereport.Data_Supplier_Raw_Original__c != null && audiencereport.Data_Supplier_Raw_Original__c != '' && 
                (!masterdatasuppliers.isEmpty() && masterdatasuppliers.containsKey(audiencereport.Data_Supplier_RAW_UPPER__c))) {
                audiencereport.Data_Supplier__c = masterdatasuppliers.get(audiencereport.Data_Supplier_RAW_UPPER__c).Data_Supplier_Account__c;
                audiencereport.Data_Supplier_Error__c = null;
            }
            else {
                audiencereport.Data_Supplier_Error__c = 'Error: Data Supplier Mapping not found.';
                audiencereport.Data_Supplier__c = null;
            }
        }
    }
}