Production/01-02-2025/force-app/main/default/objects/Opportunity/fields/Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>Deal_Type__c</fullName>
    <inlineHelpText>Please choose what the deal type is. If &apos;Others&apos;, please fill in the &quot;Deal Notes&quot; field.</inlineHelpText>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Eyeota Social</fullName>
            </value>
            <value>
                <fullName>DSP CPM</fullName>
                <default>true</default>
                <label>DSP CPM</label>
            </value>
            <value>
                <fullName>DSP Flat Fee</fullName>
            </value>
            <value>
                <fullName>DMP CPM</fullName>
            </value>
            <value>
                <fullName>DMP Flat Fee</fullName>
            </value>
            <value>
                <fullName>PDMP</fullName>
            </value>
            <value>
                <fullName>Site Optimization Subscription</fullName>
            </value>
            <value>
                <fullName>On-boarding Subscription</fullName>
            </value>
            <value>
                <fullName>Distribution Subscription</fullName>
            </value>
            <value>
                <fullName>OOH Media Owner Licensed</fullName>
            </value>
            <value>
                <fullName>Bespoke</fullName>
            </value>
            <value>
                <fullName>POC</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>CPM</fullName>
                <isActive>false</isActive>
                <label>CPM</label>
            </value>
            <value>
                <fullName>Flat Fee</fullName>
                <isActive>false</isActive>
                <label>Flat Fee</label>
            </value>
            <value>
                <fullName>Others</fullName>
                <isActive>false</isActive>
                <label>Others</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Opportunity/fields/Opportunity_ID__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_ID__c</fullName>
    <formula>CASESAFEID(Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity ID</label>
    <type>Text</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Opportunity/fields/Opportunity_Source__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Source__c</fullName>
    <label>Opportunity Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Data Desk</fullName>
            </value>
            <value>
                <fullName>Sales Rep</fullName>
                <default>true</default>
                <label>Sales Rep</label>
            </value>
            <value>
                <fullName>Platform Rep</fullName>
            </value>
            <value>
                <fullName>Client Direct</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>DMP</fullName>
            </value>
            <value>
                <fullName>Supplier/Partner</fullName>
            </value>
            <value>
                <fullName>Dun &amp; Bradstreet</fullName>
            </value>
            <value>
                <fullName>Eyeota</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Segment_Brief_Tracking__c/Segment_Brief_Tracking__c.object-meta.xml
<CustomObject>
    <description>Tracks every Segment Brief sent to new/existing clients.</description>
    <label>Segment Brief Tracking</label>
    <nameField>
        <label>Segment Brief Tracking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segment Briefs Tracking</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sandbox/02-12-2025/force-app/main/default/objects/Segment_Brief_Tracking__c/fields/Opportunity_ID__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_ID__c</fullName>
    <label>Opportunity ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Segment_Brief_Tracking__c/fields/Segment_Name__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This links the briefs to our sales numbers via the Segment Name</description>
    <label>Segment Category Mapping</label>
    <referenceTo>Segment_Category_Mapping__c</referenceTo>
    <relationshipLabel>Segment Briefs Tracking</relationshipLabel>
    <relationshipName>Segment_Briefs_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Segment_Brief_Tracking__c/fields/Segment_Name_For_Upload__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name_For_Upload__c</fullName>
    <label>Segment Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Segment_Category_Mapping__c/Segment_Category_Mapping__c.object-meta.xml
<CustomObject>
    <label>Segments Database</label>
    <nameField>
        <displayFormat>SC-{0000000000}</displayFormat>
        <label>Segment Category Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments Database</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Production/01-02-2025/force-app/main/default/objects/Segment_Category_Mapping__c/fields/Segment_Name__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name__c</fullName>
    <externalId>true</externalId>
    <label>Segment Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/04-19-2025/force-app/main/default/classes/Segment_Brief_TrackingTest.cls
@isTest
private class Segment_Brief_TrackingTest {
static testMethod void Segment_Brief_TrackingTest() {
 
        
        //create Opportunity for mapping
        Opportunity Opp = new Opportunity(Name='Test Opportunity', StageName='Closed Won', CloseDate=Date.parse('01/01/2016'), Deal_Type__c='DSP CPM', Opportunity_Source__c='Data Desk');
        Insert Opp;
        
        
        // create Segment Category Mapping Records for mapping
        Segment_Category_Mapping__c SegCatMap = new Segment_Category_Mapping__c();
        SegCatMap.Segment_Name__c='Test Account';
        Insert SegCatMap;


        // add 200 Segment Brief Tracking to the list to be inserted
        Segment_Brief_Tracking__c SegBriefUpload = new Segment_Brief_Tracking__c(Segment_Name_For_Upload__c='Test Account',
        Opportunity_ID__c=Opp.Id);
        Insert SegBriefUpload;
        Segment_Brief_Tracking__c SegBriefUploadError = new Segment_Brief_Tracking__c(Segment_Name_For_Upload__c='Test Account Error',
        Opportunity_ID__c=Opp.Id);
        Insert SegBriefUploadError;

       }
    }