Sandbox/07-02-2025/force-app/main/default/objects/Mapping_Dashboard_Emails__c/Mapping_Dashboard_Emails__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Email Alerts to be received by Emails managed in this Custom Setting.</description>
    <label>Mapping Dashboard Emails</label>
</CustomObject>

Sandbox/07-04-2025/force-app/main/default/objects/Mapping_Dashboard_Emails__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Email Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Sales_Database__c/Sales_Database__c.object-meta.xml
<CustomObject>
    <label>Sales Database</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Sales Database Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Databases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sandbox/07-02-2025/force-app/main/default/objects/Sales_Database__c/fields/Date_Invoiced__c.field-meta.xml
<CustomField>
    <fullName>Date_Invoiced__c</fullName>
    <label>Date Invoiced</label>
    <type>Date</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Sales_Database__c/fields/Platform_Error__c.field-meta.xml
<CustomField>
    <fullName>Platform_Error__c</fullName>
    <label>Platform Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Sales_Database__c/fields/Platform_Raw__c.field-meta.xml
<CustomField>
    <fullName>Platform_Raw__c</fullName>
    <label>Platform Raw</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/classes/ProcessSalesDatabaseScriptBatch.cls
global class ProcessSalesDatabaseScriptBatch implements Database.Batchable<sObject>{
    
    global Date selDate;
    global String objName;
    
    //Added by Rajesh 23rd Aug 2017, adding Invoice Date assigned by Antony
    global Date selInvDate;
    
    public ProcessSalesDatabaseScriptBatch(date selDate, date selInvDate, String objName){

        this.selDate = selDate;
        this.selInvDate = selInvDate;
        this.objName = objName;

    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        /*
        String query   = 'select Id, Platform_Error__c, Platform_Raw__c ';  
               query += 'from Sales_Database__c Where Date__c >=: selDate AND Date__c <= TODAY';
        */
        
        String query   = 'select Id, Platform_Error__c, Platform_Raw__c from Sales_Database__c Where '; 
        
        if(selDate != null && selInvDate != null){
            query += ' (Date__c >=: selDate AND Date__c <= TODAY) ';
            query += ' OR (Date_Invoiced__c >=: selInvDate AND Date_Invoiced__c <= TODAY) ';
        }else if(selDate != null && selInvDate == null){
            query += ' (Date__c >=: selDate AND Date__c <= TODAY) ';
        }else if(selDate == null && selInvDate != null){
            query += ' (Date_Invoiced__c >=: selInvDate AND Date_Invoiced__c <= TODAY) ';
        }
        
        return Database.getQueryLocator(query);
    
    }
    
    global void execute(Database.BatchableContext BC, List<Sales_Database__c> scope){

        if(scope.size()>0){
            update scope;
        }

    }
    
    global void finish(Database.BatchableContext BC){

        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
    
    //Add emails from custom setting
        Map<String,Mapping_Dashboard_Emails__c> mcs = Mapping_Dashboard_Emails__c.getall();
              
        for(Mapping_Dashboard_Emails__c emailList:mcs.values()){
     
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setToAddresses(new list<string>{emailList.Email_Address__c}); 
            mail.setSubject(objName+' Update Information');
            String body = 'Dear '+ emailList.Name +', ';
            body += '<br/> <br/>';
            body += objName +' Records successfully Updated';
            body += '<br/> <br/>';
            body += 'Thanks';
        
            mail.setHtmlBody(body);
            //Add email to the master list
            mails.add(mail);
    }

        //Send all emails in the master list
        Messaging.sendEmail(mails);

    }
     
}