Sandbox/07-02-2025/force-app/main/default/objects/Mapping_Dashboard_Emails__c/Mapping_Dashboard_Emails__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Email Alerts to be received by Emails managed in this Custom Setting.</description>
    <label>Mapping Dashboard Emails</label>
</CustomObject>

Sandbox/07-04-2025/force-app/main/default/objects/Mapping_Dashboard_Emails__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Email Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Sales_Database__c/Sales_Database__c.object-meta.xml
<CustomObject>
    <label>Sales Database</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Sales Database Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Databases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sandbox/07-02-2025/force-app/main/default/classes/ProcessSalesDatabaseScriptBatchTest.cls
@isTest
public class ProcessSalesDatabaseScriptBatchTest {
    
    static testmethod void test1(){
        Sales_Database__c sd=new Sales_Database__c();
        sd.Date__c=date.today();
        insert sd;
        
        Mapping_Dashboard_Emails__c mappDash = new Mapping_Dashboard_Emails__c(name='test1',Email_Address__c='test@gmail.com');
        insert mappDash;
        
        ProcessSalesDatabaseScriptBatch obj=new ProcessSalesDatabaseScriptBatch(date.today(),date.today(),'test');
        test.startTest();
            DataBase.executeBatch(obj);
        test.stopTest();
    }
    static testmethod void test2(){
        Sales_Database__c sd=new Sales_Database__c();
        sd.Date__c=date.today();
        insert sd;
        
        ProcessSalesDatabaseScriptBatch obj=new ProcessSalesDatabaseScriptBatch(null,date.today(),'test');
        test.startTest();
        DataBase.executeBatch(obj);
        test.stopTest();
    }
    static testmethod void test3(){
        Sales_Database__c sd=new Sales_Database__c();
        sd.Date__c=date.today();
        insert sd;
        
        ProcessSalesDatabaseScriptBatch obj=new ProcessSalesDatabaseScriptBatch(date.today(),null,'test');
        test.startTest();
        DataBase.executeBatch(obj);
        test.stopTest();
    }
}