Sandbox/07-02-2025/force-app/main/default/objects/Mapping_Dashboard_Emails__c/Mapping_Dashboard_Emails__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Email Alerts to be received by Emails managed in this Custom Setting.</description>
    <label>Mapping Dashboard Emails</label>
</CustomObject>

Sandbox/07-04-2025/force-app/main/default/objects/Mapping_Dashboard_Emails__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Email Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Supply_Database__c/Supply_Database__c.object-meta.xml
<CustomObject>
    <label>Supply Database</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Supply Database Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supply Databases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Production/01-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Data_Supplier_Raw__c.field-meta.xml
<CustomField>
    <fullName>Data_Supplier_Raw__c</fullName>
    <description>Data Supplier Raw Input converted to Upper Case for Comparison.</description>
    <inlineHelpText>Data Supplier Raw Input converted to Upper Case</inlineHelpText>
    <label>Data Supplier Raw</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Supply_Database__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date of the Buy</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Supply_Database__c/fields/Segment_Name_Supply_Raw__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name_Supply_Raw__c</fullName>
    <label>Segment Name (Supply) Raw</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Target_Country_Raw__c.field-meta.xml
<CustomField>
    <fullName>Target_Country_Raw__c</fullName>
    <description>Target Country Raw Input field from Supply Database</description>
    <inlineHelpText>Target Country Raw Input field from Supply Database</inlineHelpText>
    <label>Target Country Raw</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/classes/ProcessSupplyDatabaseScriptBatch.cls
global class ProcessSupplyDatabaseScriptBatch implements Database.Batchable<sObject>{
    
    global Date selDate;
    global String objName;
    
    public ProcessSupplyDatabaseScriptBatch(date selDate,String objName){
    
    this.selDate = selDate;
        this.objName = objName;

    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){

       String query   = 'select Id,Data_Supplier_Raw__c,Segment_Name_Supply_Raw__c,Target_Country_Raw__c ';
               query += 'from Supply_Database__c Where Date__c >=: selDate AND Date__c <= TODAY';
        return Database.getQueryLocator(query);

    }
    
    global void execute(Database.BatchableContext BC, List<Supply_Database__c> scope){

        if(scope.size()>0)
            update scope;
        
    }

    global void finish(Database.BatchableContext BC){

        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();

    //Add emails from custom setting
        Map<String,Mapping_Dashboard_Emails__c> mcs = Mapping_Dashboard_Emails__c.getall();
              
        for(Mapping_Dashboard_Emails__c emailList:mcs.values()){    

            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setToAddresses(new list<string>{emailList.Email_Address__c}); 
            mail.setSubject(objName+' Update Information');
            String body = 'Dear '+ emailList.Name +', ';
            body += '<br/> <br/>';
            body += objName +' Records successfully Updated';
            body += '<br/> <br/>';
            body += 'Thanks';
        
            mail.setHtmlBody(body);
            //Add email to the master list
            mails.add(mail);
    }

        //Send all emails in the master list
        Messaging.sendEmail(mails);

    }
     
}