Sandbox/07-04-2025/force-app/main/default/objects/Segment_Revenue_Transaction__c/Segment_Revenue_Transaction__c.object-meta.xml
<CustomObject>
    <description>Join Object between Sales and Supply Databases.</description>
    <label>Segment Revenue Transaction</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>Segment Transactions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segment Revenue Transactions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sandbox/07-02-2025/force-app/main/default/objects/Segment_Revenue_Transaction__c/fields/Total_Adjustments__c.field-meta.xml
<CustomField>
    <fullName>Total_Adjustments__c</fullName>
    <label>Total Adjustments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Segment_Revenue_Transaction__c/fields/Total_Adjustments_NEW__c.field-meta.xml
<CustomField>
    <fullName>Total_Adjustments_NEW__c</fullName>
    <label>Total Adjustments NEW</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Currency</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Supply_Database__c/Supply_Database__c.object-meta.xml
<CustomObject>
    <label>Supply Database</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Supply Database Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supply Databases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sandbox/02-12-2025/force-app/main/default/objects/Supply_Database__c/fields/Segment_Revenue_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Segment_Revenue_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Join to Segment Revenue Transaction Object</description>
    <inlineHelpText>Join to Segment Revenue Transaction Object</inlineHelpText>
    <label>Segment Revenue Transaction</label>
    <referenceTo>Segment_Revenue_Transaction__c</referenceTo>
    <relationshipLabel>Supply Databases</relationshipLabel>
    <relationshipName>Supply_Databases</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Total_Adjustments__c.field-meta.xml
<CustomField>
    <fullName>Total_Adjustments__c</fullName>
    <formula>X33Across_Adjustment_USD__c + Supplier_Gross_Earnings_Retrospective__c + ID_Graph_Adjustment_USD__c + ShareThis_Adjustment_USD__c + TapAd_Adjustment_USD__c + Tech_Cost_Adjustment_USD__c + ComScore_Adjustment_USD__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Adjustments</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Currency</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Total_Adjustments_NEW__c.field-meta.xml
<CustomField>
    <fullName>Total_Adjustments_NEW__c</fullName>
    <formula>X33Across_Adjustment_USD_NEW__c + Digital_Envoy_Adjustment_USD_NEW__c + ID_Graph_Adjustment_USD_NEW__c + ShareThis_Adjustment_USD_NEW__c + TapAd_Adjustment_USD_NEW__c + Tech_Cost_Adjustment_USD_NEW__c + Other_1_Adjustment_USD_NEW__c + Other_2_Adjustment_USD_NEW__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Adjustments NEW</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/classes/UpdateSegmentTotalAdjustment.cls
global with sharing class UpdateSegmentTotalAdjustment implements Database.Batchable<sObject> {
    public Set<Id> setOfIds {get; set;}
    public UpdateSegmentTotalAdjustment(Set<Id> setOfIds){
       this.setOfIds = setOfIds;
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id FROM Segment_Revenue_Transaction__c';

        if(setOfIds.size() > 0){
            query += ' WHERE Id IN :setOfIds';
        }

        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<Segment_Revenue_Transaction__c> records){
        Set<Id> segmentRevenueTransactionIds = new Set<Id>();
        for(Segment_Revenue_Transaction__c record : records){
            segmentRevenueTransactionIds.add(record.Id);
        }

        List<AggregateResult> results =  [SELECT Segment_Revenue_Transaction__c, SUM(Total_Adjustments__c) totalAdjustments, SUM(Total_Adjustments_NEW__c) totalAdjustmentsNew FROM Supply_Database__c WHERE Segment_Revenue_Transaction__c IN :segmentRevenueTransactionIds GROUP BY Segment_Revenue_Transaction__c];

        if(results.size() > 0){
            List<Segment_Revenue_Transaction__c> segments = new List<Segment_Revenue_Transaction__c>();
            for (AggregateResult result : results){
                Segment_Revenue_Transaction__c segment = new Segment_Revenue_Transaction__c(
                    Id = (Id) result.get('Segment_Revenue_Transaction__c'),
                    Total_Adjustments__c = (Double) result.get('totalAdjustments'),
                    Total_Adjustments_NEW__c = (-1 * (Double) result.get('totalAdjustmentsNew'))
                );
                segments.add(segment);
            }
    
            System.debug('segments segments segments' + segments);
    
            if( segments.size() > 0 ){  
                update segments;
            }
        }
    }   

    global void finish(Database.BatchableContext bc){
        //Finish
    }    
}