Sandbox/07-04-2025/force-app/main/default/objects/Segment_Revenue_Transaction__c/Segment_Revenue_Transaction__c.object-meta.xml
<CustomObject>
    <description>Join Object between Sales and Supply Databases.</description>
    <label>Segment Revenue Transaction</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>Segment Transactions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segment Revenue Transactions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sandbox/07-02-2025/force-app/main/default/objects/Segment_Revenue_Transaction__c/fields/Total_Adjustments__c.field-meta.xml
<CustomField>
    <fullName>Total_Adjustments__c</fullName>
    <label>Total Adjustments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Segment_Revenue_Transaction__c/fields/Total_Adjustments_NEW__c.field-meta.xml
<CustomField>
    <fullName>Total_Adjustments_NEW__c</fullName>
    <label>Total Adjustments NEW</label>
    <precision>16</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Supply_Database__c/Supply_Database__c.object-meta.xml
<CustomObject>
    <label>Supply Database</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Supply Database Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supply Databases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sandbox/02-12-2025/force-app/main/default/objects/Supply_Database__c/fields/ComScore_Adjustment_USD__c.field-meta.xml
<CustomField>
    <fullName>ComScore_Adjustment_USD__c</fullName>
    <label>Other Adjustment (USD)</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Supply_Database__c/fields/Digital_Envoy_Adjustment_USD_NEW__c.field-meta.xml
<CustomField>
    <fullName>Digital_Envoy_Adjustment_USD_NEW__c</fullName>
    <label>Digital Envoy Adjustment (USD) NEW</label>
    <precision>16</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Supply_Database__c/fields/ID_Graph_Adjustment_USD__c.field-meta.xml
<CustomField>
    <fullName>ID_Graph_Adjustment_USD__c</fullName>
    <label>ID Graph Adjustment (USD)</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Supply_Database__c/fields/ID_Graph_Adjustment_USD_NEW__c.field-meta.xml
<CustomField>
    <fullName>ID_Graph_Adjustment_USD_NEW__c</fullName>
    <label>ID Graph Adjustment (USD) NEW</label>
    <precision>16</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Supply_Database__c/fields/Other_1_Adjustment_USD_NEW__c.field-meta.xml
<CustomField>
    <fullName>Other_1_Adjustment_USD_NEW__c</fullName>
    <label>Other 1 Adjustment (USD) NEW</label>
    <precision>16</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Supply_Database__c/fields/Other_2_Adjustment_USD_NEW__c.field-meta.xml
<CustomField>
    <fullName>Other_2_Adjustment_USD_NEW__c</fullName>
    <label>Other 2 Adjustment (USD) NEW</label>
    <precision>16</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Supply_Database__c/fields/Segment_Revenue_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Segment_Revenue_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Join to Segment Revenue Transaction Object</description>
    <inlineHelpText>Join to Segment Revenue Transaction Object</inlineHelpText>
    <label>Segment Revenue Transaction</label>
    <referenceTo>Segment_Revenue_Transaction__c</referenceTo>
    <relationshipLabel>Supply Databases</relationshipLabel>
    <relationshipName>Supply_Databases</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Supply_Database__c/fields/ShareThis_Adjustment_USD__c.field-meta.xml
<CustomField>
    <fullName>ShareThis_Adjustment_USD__c</fullName>
    <label>ShareThis Adjustment (USD)</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Supply_Database__c/fields/ShareThis_Adjustment_USD_NEW__c.field-meta.xml
<CustomField>
    <fullName>ShareThis_Adjustment_USD_NEW__c</fullName>
    <label>ShareThis Adjustment (USD) NEW</label>
    <precision>16</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Supplier_Gross_Earnings_Retrospective__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Gross_Earnings_Retrospective__c</fullName>
    <description>For data before 2016 and for Digital Envoy adjustments.</description>
    <label>Digital Envoy Adjustment (USD)</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Supply_Database__c/fields/TapAd_Adjustment_USD__c.field-meta.xml
<CustomField>
    <fullName>TapAd_Adjustment_USD__c</fullName>
    <label>TapAd Adjustment (USD)</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Supply_Database__c/fields/TapAd_Adjustment_USD_NEW__c.field-meta.xml
<CustomField>
    <fullName>TapAd_Adjustment_USD_NEW__c</fullName>
    <label>TapAd Adjustment (USD) NEW</label>
    <precision>16</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Supply_Database__c/fields/Tech_Cost_Adjustment_USD__c.field-meta.xml
<CustomField>
    <fullName>Tech_Cost_Adjustment_USD__c</fullName>
    <label>Tech Cost Adjustment (USD)</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Tech_Cost_Adjustment_USD_NEW__c.field-meta.xml
<CustomField>
    <fullName>Tech_Cost_Adjustment_USD_NEW__c</fullName>
    <label>Tech Cost Adjustment (USD) NEW</label>
    <precision>16</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Total_Adjustments__c.field-meta.xml
<CustomField>
    <fullName>Total_Adjustments__c</fullName>
    <formula>X33Across_Adjustment_USD__c + Supplier_Gross_Earnings_Retrospective__c + ID_Graph_Adjustment_USD__c + ShareThis_Adjustment_USD__c + TapAd_Adjustment_USD__c + Tech_Cost_Adjustment_USD__c + ComScore_Adjustment_USD__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Adjustments</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Currency</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Total_Adjustments_NEW__c.field-meta.xml
<CustomField>
    <fullName>Total_Adjustments_NEW__c</fullName>
    <formula>X33Across_Adjustment_USD_NEW__c + Digital_Envoy_Adjustment_USD_NEW__c + ID_Graph_Adjustment_USD_NEW__c + ShareThis_Adjustment_USD_NEW__c + TapAd_Adjustment_USD_NEW__c + Tech_Cost_Adjustment_USD_NEW__c + Other_1_Adjustment_USD_NEW__c + Other_2_Adjustment_USD_NEW__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Adjustments NEW</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Supply_Database__c/fields/X33Across_Adjustment_USD__c.field-meta.xml
<CustomField>
    <fullName>X33Across_Adjustment_USD__c</fullName>
    <label>33Across Adjustment (USD)</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Supply_Database__c/fields/X33Across_Adjustment_USD_NEW__c.field-meta.xml
<CustomField>
    <fullName>X33Across_Adjustment_USD_NEW__c</fullName>
    <defaultValue>0</defaultValue>
    <label>33Across Adjustment (USD) NEW</label>
    <precision>16</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/classes/SupplyDBHandler.cls
public with sharing class SupplyDBHandler {
    public static void onAfterUpdate(List<Supply_Database__c> supplyDatabases, Map<Id,Supply_Database__c> oldSupplyDatabases){
        List<Id> segmentRevenueTransactionIds = new List<Id>();
        for(Supply_Database__c supplyDatabase : supplyDatabases){
            if( supplyDatabase.X33Across_Adjustment_USD__c != oldSupplyDatabases.get(supplyDatabase.Id).X33Across_Adjustment_USD__c || 
                supplyDatabase.Supplier_Gross_Earnings_Retrospective__c != oldSupplyDatabases.get(supplyDatabase.Id).Supplier_Gross_Earnings_Retrospective__c || 
                supplyDatabase.ID_Graph_Adjustment_USD__c  != oldSupplyDatabases.get(supplyDatabase.Id).ID_Graph_Adjustment_USD__c || 
                supplyDatabase.ShareThis_Adjustment_USD__c  != oldSupplyDatabases.get(supplyDatabase.Id).ShareThis_Adjustment_USD__c || 
                supplyDatabase.TapAd_Adjustment_USD__c  != oldSupplyDatabases.get(supplyDatabase.Id).TapAd_Adjustment_USD__c || 
                supplyDatabase.Tech_Cost_Adjustment_USD__c  != oldSupplyDatabases.get(supplyDatabase.Id).Tech_Cost_Adjustment_USD__c ||
                supplyDatabase.ComScore_Adjustment_USD__c != oldSupplyDatabases.get(supplyDatabase.Id).ComScore_Adjustment_USD__c || 
                supplyDatabase.X33Across_Adjustment_USD_NEW__c != oldSupplyDatabases.get(supplyDatabase.Id).X33Across_Adjustment_USD_NEW__c || 
                supplyDatabase.Digital_Envoy_Adjustment_USD_NEW__c != oldSupplyDatabases.get(supplyDatabase.Id).Digital_Envoy_Adjustment_USD_NEW__c || 
                supplyDatabase.ID_Graph_Adjustment_USD_NEW__c  != oldSupplyDatabases.get(supplyDatabase.Id).ID_Graph_Adjustment_USD_NEW__c || 
                supplyDatabase.ShareThis_Adjustment_USD_NEW__c  != oldSupplyDatabases.get(supplyDatabase.Id).ShareThis_Adjustment_USD_NEW__c || 
                supplyDatabase.TapAd_Adjustment_USD_NEW__c  != oldSupplyDatabases.get(supplyDatabase.Id).TapAd_Adjustment_USD_NEW__c || 
                supplyDatabase.Tech_Cost_Adjustment_USD_NEW__c  != oldSupplyDatabases.get(supplyDatabase.Id).Tech_Cost_Adjustment_USD_NEW__c ||
                supplyDatabase.Other_1_Adjustment_USD_NEW__c != oldSupplyDatabases.get(supplyDatabase.Id).Other_1_Adjustment_USD_NEW__c ||
                supplyDatabase.Other_2_Adjustment_USD_NEW__c != oldSupplyDatabases.get(supplyDatabase.Id).Other_2_Adjustment_USD_NEW__c ){
                    
                // Double X33AcrossAdjustmentUSD = supplyDatabase.X33Across_Adjustment_USD__c != null ? supplyDatabase.X33Across_Adjustment_USD__c : 0;
                // Double SupplierGrossEarningsRetrospective = supplyDatabase.Supplier_Gross_Earnings_Retrospective__c != null ? supplyDatabase.Supplier_Gross_Earnings_Retrospective__c : 0;
                // Double IDGraphAdjustmentUSD = supplyDatabase.ID_Graph_Adjustment_USD__c != null ? supplyDatabase.ID_Graph_Adjustment_USD__c : 0;
                // Double ShareThisAdjustmentUSD = supplyDatabase.ShareThis_Adjustment_USD__c != null ? supplyDatabase.ShareThis_Adjustment_USD__c : 0;
                // Double TapAdAdjustmentUSD = supplyDatabase.TapAd_Adjustment_USD__c != null ? supplyDatabase.TapAd_Adjustment_USD__c : 0;
                // Double TechCostAdjustmentUSD = supplyDatabase.Tech_Cost_Adjustment_USD__c != null ? supplyDatabase.Tech_Cost_Adjustment_USD__c : 0;
                // Double ComScoreAdjustmentUSD = supplyDatabase.ComScore_Adjustment_USD__c != null ? supplyDatabase.ComScore_Adjustment_USD__c : 0;

                // totalAdjustments = X33AcrossAdjustmentUSD + SupplierGrossEarningsRetrospective + IDGraphAdjustmentUSD + ShareThisAdjustmentUSD + TapAdAdjustmentUSD + TechCostAdjustmentUSD + ComScoreAdjustmentUSD;

                if( !segmentRevenueTransactionIds.contains(supplyDatabase.Segment_Revenue_Transaction__c) ){
                    segmentRevenueTransactionIds.add(supplyDatabase.Segment_Revenue_Transaction__c);
                }
            }

            // if( supplyDatabase.X33Across_Adjustment_USD_NEW__c != oldSupplyDatabases.get(supplyDatabase.Id).X33Across_Adjustment_USD_NEW__c || 
            //     supplyDatabase.Digital_Envoy_Adjustment_USD_NEW__c != oldSupplyDatabases.get(supplyDatabase.Id).Digital_Envoy_Adjustment_USD_NEW__c || 
            //     supplyDatabase.ID_Graph_Adjustment_USD_NEW__c  != oldSupplyDatabases.get(supplyDatabase.Id).ID_Graph_Adjustment_USD_NEW__c || 
            //     supplyDatabase.ShareThis_Adjustment_USD_NEW__c  != oldSupplyDatabases.get(supplyDatabase.Id).ShareThis_Adjustment_USD_NEW__c || 
            //     supplyDatabase.TapAd_Adjustment_USD_NEW__c  != oldSupplyDatabases.get(supplyDatabase.Id).TapAd_Adjustment_USD_NEW__c || 
            //     supplyDatabase.Tech_Cost_Adjustment_USD_NEW__c  != oldSupplyDatabases.get(supplyDatabase.Id).Tech_Cost_Adjustment_USD_NEW__c ||
            //     supplyDatabase.Other_1_Adjustment_USD_NEW__c != oldSupplyDatabases.get(supplyDatabase.Id).Other_1_Adjustment_USD_NEW__c ||
            //     supplyDatabase.Other_2_Adjustment_USD_NEW__c != oldSupplyDatabases.get(supplyDatabase.Id).Other_2_Adjustment_USD_NEW__c ){
            
            //     Double X33AcrossAdjustmentUSDNEW = supplyDatabase.X33Across_Adjustment_USD_NEW__c != null ? supplyDatabase.X33Across_Adjustment_USD_NEW__c : 0;
            //     Double DigitalEnvoyAdjustmentUSDNEW = supplyDatabase.Digital_Envoy_Adjustment_USD_NEW__c != null ? supplyDatabase.Digital_Envoy_Adjustment_USD_NEW__c : 0;
            //     Double IDGraphAdjustmentUSDNEW = supplyDatabase.ID_Graph_Adjustment_USD_NEW__c != null ? supplyDatabase.ID_Graph_Adjustment_USD_NEW__c : 0;
            //     Double ShareThisAdjustmentUSDNEW = supplyDatabase.ShareThis_Adjustment_USD_NEW__c != null ? supplyDatabase.ShareThis_Adjustment_USD_NEW__c : 0;
            //     Double TapAdAdjustmentUSDNEW = supplyDatabase.TapAd_Adjustment_USD_NEW__c != null ? supplyDatabase.TapAd_Adjustment_USD_NEW__c : 0;
            //     Double TechCostAdjustmentUSDNEW = supplyDatabase.Tech_Cost_Adjustment_USD_NEW__c != null ? supplyDatabase.Tech_Cost_Adjustment_USD_NEW__c : 0;
            //     Double Other1AdjustmentUSDNEW = supplyDatabase.Other_1_Adjustment_USD_NEW__c != null ? supplyDatabase.Other_1_Adjustment_USD_NEW__c : 0;
            //     Double Other2AdjustmentUSDNEW = supplyDatabase.Other_2_Adjustment_USD_NEW__c != null ? supplyDatabase.Other_2_Adjustment_USD_NEW__c : 0;

            //     totalAdjustmentsNew = X33AcrossAdjustmentUSDNEW + DigitalEnvoyAdjustmentUSDNEW + IDGraphAdjustmentUSDNEW + ShareThisAdjustmentUSDNEW + TapAdAdjustmentUSDNEW + TechCostAdjustmentUSDNEW + Other1AdjustmentUSDNEW + Other2AdjustmentUSDNEW;
            
            // }

            if(segmentRevenueTransactionIds.size() > 0){
                List<AggregateResult> results =  [SELECT Segment_Revenue_Transaction__c, SUM(Total_Adjustments__c) totalAdjustments, SUM(Total_Adjustments_NEW__c) totalAdjustmentsNew FROM Supply_Database__c WHERE Segment_Revenue_Transaction__c IN :segmentRevenueTransactionIds GROUP BY Segment_Revenue_Transaction__c];
                List<Segment_Revenue_Transaction__c> segments = new List<Segment_Revenue_Transaction__c>();
                for (AggregateResult result : results){
                    Segment_Revenue_Transaction__c segment = new Segment_Revenue_Transaction__c(
                        Id = (Id) result.get('Segment_Revenue_Transaction__c'),
                        Total_Adjustments__c = (Double) result.get('totalAdjustments'),
                        Total_Adjustments_NEW__c = (Double) result.get('totalAdjustmentsNew')
                    );
                    segments.add(segment);
                }

                System.debug('segments segments segments' + segments);

                if( segments.size() > 0 ){  
                    update segments;
                }
            }
        }
    }
}