Sandbox/02-12-2025/force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Competitor (no emails)</fullName>
            </value>
            <value>
                <fullName>Ad Network</fullName>
            </value>
            <value>
                <fullName>Ad Server</fullName>
            </value>
            <value>
                <fullName>Advertiser</fullName>
            </value>
            <value>
                <fullName>Data Supplier</fullName>
            </value>
            <value>
                <fullName>Data Buyer</fullName>
            </value>
            <value>
                <fullName>DMP/Data Specialist</fullName>
            </value>
            <value>
                <fullName>DSP</fullName>
            </value>
            <value>
                <fullName>Media Agency</fullName>
            </value>
            <value>
                <fullName>Trading Desk</fullName>
            </value>
            <value>
                <fullName>PMP</fullName>
            </value>
            <value>
                <fullName>Publisher</fullName>
            </value>
            <value>
                <fullName>SSP</fullName>
            </value>
            <value>
                <fullName>Advisory Board Member</fullName>
            </value>
            <value>
                <fullName>Board of Directors</fullName>
            </value>
            <value>
                <fullName>Competitor Investor</fullName>
            </value>
            <value>
                <fullName>Current Investor</fullName>
            </value>
            <value>
                <fullName>Potential Investor</fullName>
            </value>
            <value>
                <fullName>Shareholder</fullName>
            </value>
            <value>
                <fullName>Unlisted Advisor</fullName>
            </value>
            <value>
                <fullName>Industry Association</fullName>
            </value>
            <value>
                <fullName>Press</fullName>
            </value>
            <value>
                <fullName>Event Supplier</fullName>
            </value>
            <value>
                <fullName>Marketing Supplier</fullName>
            </value>
            <value>
                <fullName>General Interest</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Branded Data Partner</fullName>
            </value>
            <value>
                <fullName>Not a Supply Source</fullName>
            </value>
            <value>
                <fullName>Technology Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Account/fields/New_Flag__c.field-meta.xml
<CustomField>
    <fullName>New_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New Flag</label>
    <type>Checkbox</type>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Segment_Category_Mapping__c/Segment_Category_Mapping__c.object-meta.xml
<CustomObject>
    <label>Segments Database</label>
    <nameField>
        <displayFormat>SC-{0000000000}</displayFormat>
        <label>Segment Category Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments Database</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sandbox/07-04-2025/force-app/main/default/objects/Segment_Revenue_Transaction__c/Segment_Revenue_Transaction__c.object-meta.xml
<CustomObject>
    <description>Join Object between Sales and Supply Databases.</description>
    <label>Segment Revenue Transaction</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>Segment Transactions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segment Revenue Transactions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sandbox/07-02-2025/force-app/main/default/objects/Segment_Revenue_Transaction__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <externalId>true</externalId>
    <label>Country_Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Segment_Revenue_Transaction__c/fields/Segment_Category_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Segment_Category_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segment Category Mapping</label>
    <referenceTo>Segment_Category_Mapping__c</referenceTo>
    <relationshipLabel>Segment Revenue Transactions</relationshipLabel>
    <relationshipName>Segment_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

Production/01-02-2025/force-app/main/default/classes/TriggerUtility.cls
public with sharing Class TriggerUtility{

    public static boolean inFutureContext = false;
    public static boolean inFutureContext1 = false;
 
    public static Segment_Revenue_Transaction__c toCreateSG(Date objDate, String objCountry, String objSegmentCode){
    
        System.debug(' st.Country_Code__c  ' + objCountry );
        Segment_Revenue_Transaction__c st = new Segment_Revenue_Transaction__c();
        st.Date__c = objDate;
        st.Country_Code__c = objCountry;
        st.Segment_Category_Mapping__c = objSegmentCode;
        return st; 
    }
    
    public static Account toCreateAccount(String accName,String accountType){
        Account acc = new Account();
        acc.Name = accName;
        acc.Account_Type__c = accountType;
        acc.New_Flag__c = true;
        return acc;
    }    
}