Sandbox/02-12-2025/force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Competitor (no emails)</fullName>
            </value>
            <value>
                <fullName>Ad Network</fullName>
            </value>
            <value>
                <fullName>Ad Server</fullName>
            </value>
            <value>
                <fullName>Advertiser</fullName>
            </value>
            <value>
                <fullName>Data Supplier</fullName>
            </value>
            <value>
                <fullName>Data Buyer</fullName>
            </value>
            <value>
                <fullName>DMP/Data Specialist</fullName>
            </value>
            <value>
                <fullName>DSP</fullName>
            </value>
            <value>
                <fullName>Media Agency</fullName>
            </value>
            <value>
                <fullName>Trading Desk</fullName>
            </value>
            <value>
                <fullName>PMP</fullName>
            </value>
            <value>
                <fullName>Publisher</fullName>
            </value>
            <value>
                <fullName>SSP</fullName>
            </value>
            <value>
                <fullName>Advisory Board Member</fullName>
            </value>
            <value>
                <fullName>Board of Directors</fullName>
            </value>
            <value>
                <fullName>Competitor Investor</fullName>
            </value>
            <value>
                <fullName>Current Investor</fullName>
            </value>
            <value>
                <fullName>Potential Investor</fullName>
            </value>
            <value>
                <fullName>Shareholder</fullName>
            </value>
            <value>
                <fullName>Unlisted Advisor</fullName>
            </value>
            <value>
                <fullName>Industry Association</fullName>
            </value>
            <value>
                <fullName>Press</fullName>
            </value>
            <value>
                <fullName>Event Supplier</fullName>
            </value>
            <value>
                <fullName>Marketing Supplier</fullName>
            </value>
            <value>
                <fullName>General Interest</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Branded Data Partner</fullName>
            </value>
            <value>
                <fullName>Not a Supply Source</fullName>
            </value>
            <value>
                <fullName>Technology Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Data_Supplier_Mapping__c/Data_Supplier_Mapping__c.object-meta.xml
<CustomObject>
    <label>Data Supplier Mapping</label>
    <nameField>
        <displayFormat>DSM-{0000000000}</displayFormat>
        <label>Data Supplier Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Supplier Mappings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sandbox/07-02-2025/force-app/main/default/objects/Data_Supplier_Mapping__c/fields/Data_Supplier__c.field-meta.xml
<CustomField>
    <fullName>Data_Supplier__c</fullName>
    <formula>Data_Supplier_Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Data Supplier</label>
    <type>Text</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Data_Supplier_Mapping__c/fields/Data_Supplier_Account__c.field-meta.xml
<CustomField>
    <fullName>Data_Supplier_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Data Supplier Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Data Supplier Mappings</relationshipLabel>
    <relationshipName>Data_Supplier_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Data_Supplier_Mapping__c/fields/Data_Supplier_Raw__c.field-meta.xml
<CustomField>
    <fullName>Data_Supplier_Raw__c</fullName>
    <label>Data Supplier Raw</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Publisher_Monthly_Global__c/Publisher_Monthly_Global__c.object-meta.xml
<CustomObject>
    <label>Publisher Monthly Global</label>
    <nameField>
        <label>Publisher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publisher Monthly Global</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sandbox/02-12-2025/force-app/main/default/objects/Publisher_Monthly_Global__c/fields/Country_Raw__c.field-meta.xml
<CustomField>
    <fullName>Country_Raw__c</fullName>
    <externalId>true</externalId>
    <label>Country Raw</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Publisher_Monthly_Global__c/fields/Data_Supplier__c.field-meta.xml
<CustomField>
    <fullName>Data_Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Data Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Publisher Monthly Global</relationshipLabel>
    <relationshipName>Publisher_Monthly_Global</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Publisher_Monthly_Global__c/fields/Data_Supplier_Raw__c.field-meta.xml
<CustomField>
    <fullName>Data_Supplier_Raw__c</fullName>
    <label>Data Supplier Raw</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Publisher_Monthly_Global__c/fields/Data_Supplier_Raw_Original__c.field-meta.xml
<CustomField>
    <fullName>Data_Supplier_Raw_Original__c</fullName>
    <label>Data Supplier Raw Original</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Publisher_Monthly_Global__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <description>Revenue aggregated from Gross Supplier Earnings of Supply Database, for the Date and Data Supplier in the current record.</description>
    <label>Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Supply_Database__c/Supply_Database__c.object-meta.xml
<CustomObject>
    <label>Supply Database</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Supply Database Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supply Databases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Production/01-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Data_Supplier__c.field-meta.xml
<CustomField>
    <fullName>Data_Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Data Supplier Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supply Databases</relationshipLabel>
    <relationshipName>Supply_Databases</relationshipName>
    <type>Lookup</type>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Data_Supplier_Raw__c.field-meta.xml
<CustomField>
    <fullName>Data_Supplier_Raw__c</fullName>
    <description>Data Supplier Raw Input converted to Upper Case for Comparison.</description>
    <inlineHelpText>Data Supplier Raw Input converted to Upper Case</inlineHelpText>
    <label>Data Supplier Raw</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Data_Supplier_Raw_Original__c.field-meta.xml
<CustomField>
    <fullName>Data_Supplier_Raw_Original__c</fullName>
    <description>Data Supplier Raw Input Field (From Fugu reports)</description>
    <inlineHelpText>Data Supplier Raw Input Field (From Fugu reports)</inlineHelpText>
    <label>Data Supplier Raw Original</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Supply_Database__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date of the Buy</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Target_Country_Raw__c.field-meta.xml
<CustomField>
    <fullName>Target_Country_Raw__c</fullName>
    <description>Target Country Raw Input field from Supply Database</description>
    <inlineHelpText>Target Country Raw Input field from Supply Database</inlineHelpText>
    <label>Target Country Raw</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Uniques__c.field-meta.xml
<CustomField>
    <fullName>Uniques__c</fullName>
    <label>Uniques</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/classes/PublisherMonthlyGlobalTest.cls
@isTest
public class PublisherMonthlyGlobalTest
{
        static testmethod void PublisherMonthlyGlobalTest(){   
            Account acc = new Account();
            acc.Name='ABC';
            acc.Account_Type__c='Data Supplier';
            insert acc; 
            
            Data_Supplier_Mapping__c dataSupplierMappings = new Data_Supplier_Mapping__c();
            dataSupplierMappings.Data_Supplier_Raw__c ='TEST DATA SUPPLIER';
            dataSupplierMappings.Data_Supplier_Account__c=acc.Id;
            insert dataSupplierMappings;
            
             List<Data_Supplier_Mapping__c> samples = [Select Name, Id, Data_Supplier_Raw__c, Data_Supplier__c From Data_Supplier_Mapping__c WHERE Id = :dataSupplierMappings.Id];
			 System.debug('samples samples samples' +  samples);
            
            Publisher_Monthly_Global__c Pb1 = new Publisher_Monthly_Global__c();
            Pb1.Name='Booksworth';
            Pb1.Date__c=date.today();
            Pb1.Country_Raw__c='Australian';
            Pb1.Revenue__c=50.50;
            pb1.Data_Supplier__c=acc.Id;
            pb1.Data_Supplier_Raw_Original__c='test data supplier';
            pb1.Data_Supplier_Raw__c=pb1.Data_Supplier_Raw_Original__c;
            insert Pb1;

            Supply_Database__c Sup = new Supply_Database__c();
            Sup.Target_Country_Raw__c='New Mexico';
            Sup.Uniques__c=5000;
            Sup.Data_Supplier_Raw__c='';
            Sup.Date__c=Pb1.Date__c;
            Insert sup;
        }
}