Sandbox/07-04-2025/force-app/main/default/objects/Adjustment_Transaction__c/Adjustment_Transaction__c.object-meta.xml
<CustomObject>
    <label>Adjustment Transaction</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>Adjustment Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustment Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Production/01-02-2025/force-app/main/default/objects/Adjustment_Transaction__c/fields/Is_Updated__c.field-meta.xml
<CustomField>
    <fullName>Is_Updated__c</fullName>
    <formula>Revenue_Amount__c ==  Supply_Database__r.Gross_Earnings_Calc_USD_For_Export__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Updated</label>
    <type>Checkbox</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Adjustment_Transaction__c/fields/Revenue_Amount__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Amount__c</fullName>
    <label>Revenue Amount</label>
    <precision>16</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Adjustment_Transaction__c/fields/Supply_Database__c.field-meta.xml
<CustomField>
    <fullName>Supply_Database__c</fullName>
    <label>Supply Database</label>
    <referenceTo>Supply_Database__c</referenceTo>
    <relationshipLabel>Adjustment Transactions</relationshipLabel>
    <relationshipName>Adjustment_Transactions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Supply_Database__c/Supply_Database__c.object-meta.xml
<CustomObject>
    <label>Supply Database</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Supply Database Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supply Databases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sandbox/07-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Gross_Earnings_Calc_USD_For_Export__c.field-meta.xml
<CustomField>
    <fullName>Gross_Earnings_Calc_USD_For_Export__c</fullName>
    <formula>Supplier_Gross_Earnings__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gross Earnings Calc USD - For Export</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

Sandbox/04-19-2025/force-app/main/default/classes/AdjTransactionUpdatedBatch.cls
global class AdjTransactionUpdatedBatch implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id, Supply_Database__r.Gross_Earnings_Calc_USD_For_Export__c FROM Adjustment_Transaction__c WHERE Is_Updated__c = false';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<Adjustment_Transaction__c> scope){
        for( Adjustment_Transaction__c record : scope ){
            record.Revenue_Amount__c = record.Supply_Database__r.Gross_Earnings_Calc_USD_For_Export__c;
        }
        update scope;
    }   

    global void finish(Database.BatchableContext bc){
        //Finish
    }    
}