Production/01-02-2025/force-app/main/default/objects/Account/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <label>Currency Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
                <default>true</default>
                <label>USD</label>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>INR</fullName>
            </value>
            <value>
                <fullName>NZD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Data_Supplier_Mapping__c/Data_Supplier_Mapping__c.object-meta.xml
<CustomObject>
    <label>Data Supplier Mapping</label>
    <nameField>
        <displayFormat>DSM-{0000000000}</displayFormat>
        <label>Data Supplier Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Supplier Mappings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Production/01-02-2025/force-app/main/default/objects/Data_Supplier_Mapping__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <formula>TEXT(Data_Supplier_Account__r.Currency_Code__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Code</label>
    <type>Text</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Data_Supplier_Mapping__c/fields/Data_Supplier_Account__c.field-meta.xml
<CustomField>
    <fullName>Data_Supplier_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Data Supplier Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Data Supplier Mappings</relationshipLabel>
    <relationshipName>Data_Supplier_Mappings</relationshipName>
    <type>Lookup</type>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Data_Supplier_Mapping__c/fields/Data_Supplier_Raw__c.field-meta.xml
<CustomField>
    <fullName>Data_Supplier_Raw__c</fullName>
    <label>Data Supplier Raw</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Segment_Category_Mapping__c/Segment_Category_Mapping__c.object-meta.xml
<CustomObject>
    <label>Segments Database</label>
    <nameField>
        <displayFormat>SC-{0000000000}</displayFormat>
        <label>Segment Category Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segments Database</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Production/01-02-2025/force-app/main/default/objects/Segment_Category_Mapping__c/fields/Segment_Key_Raw__c.field-meta.xml
<CustomField>
    <fullName>Segment_Key_Raw__c</fullName>
    <formula>UPPER( Segment_Code__c )</formula>
    <label>Segment Key Raw</label>
    <type>Text</type>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Segment_Category_Mapping__c/fields/Segment_Name__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name__c</fullName>
    <externalId>true</externalId>
    <label>Segment Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Segment_Mapping__c/Segment_Mapping__c.object-meta.xml
<CustomObject>
    <label>Segment Mapping</label>
    <nameField>
        <displayFormat>SM-{0000000000}</displayFormat>
        <label>Segment Mapping Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segment Mappings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Production/01-02-2025/force-app/main/default/objects/Segment_Mapping__c/fields/Segment_Category_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Segment_Category_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segment Category Mapping</label>
    <referenceTo>Segment_Category_Mapping__c</referenceTo>
    <relationshipName>Segment_Mapping</relationshipName>
    <type>Lookup</type>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Segment_Mapping__c/fields/Segment_Name_Sales_Raw__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name_Sales_Raw__c</fullName>
    <externalId>true</externalId>
    <label>Segment Name (Sales) Raw</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Segment_Mapping__c/fields/Segment_Name_Supply_Raw__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name_Supply_Raw__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Please upload SEGMENT KEY in this field (ALL CAPS) for supply data from October 1, 2016 onwards.</inlineHelpText>
    <label>Segment Name (Supply) Raw</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Segment_Revenue_Transaction__c/Segment_Revenue_Transaction__c.object-meta.xml
<CustomObject>
    <description>Join Object between Sales and Supply Databases.</description>
    <label>Segment Revenue Transaction</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>Segment Transactions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Segment Revenue Transactions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sandbox/01-02-2025/force-app/main/default/objects/Segment_Revenue_Transaction__c/fields/Segment_Category_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Segment_Category_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segment Category Mapping</label>
    <referenceTo>Segment_Category_Mapping__c</referenceTo>
    <relationshipLabel>Segment Revenue Transactions</relationshipLabel>
    <relationshipName>Segment_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Segment_Revenue_Transaction__c/fields/Segment_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Segment_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segment Mapping</label>
    <referenceTo>Segment_Mapping__c</referenceTo>
    <relationshipLabel>Segment Revenue Transactions</relationshipLabel>
    <relationshipName>Segment_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Segment_Revenue_Transaction__c/fields/Uniques_RollUp__c.field-meta.xml
<CustomField>
    <fullName>Uniques_RollUp__c</fullName>
    <inlineHelpText>Roll up of &quot;Net Supplier Earnings&quot; from Supply Database .it is manage by Flow.</inlineHelpText>
    <label>Uniques RollUp</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Supply_Database__c/Supply_Database__c.object-meta.xml
<CustomObject>
    <label>Supply Database</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Supply Database Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supply Databases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Sandbox/07-04-2025/force-app/main/default/objects/Supply_Database__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <label>Currency Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Billing_Currency_Code</valueSetName>
    </valueSet>
</CustomField>

Production/01-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Data_Supplier_Raw__c.field-meta.xml
<CustomField>
    <fullName>Data_Supplier_Raw__c</fullName>
    <description>Data Supplier Raw Input converted to Upper Case for Comparison.</description>
    <inlineHelpText>Data Supplier Raw Input converted to Upper Case</inlineHelpText>
    <label>Data Supplier Raw</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Data_Supplier_Raw_Original__c.field-meta.xml
<CustomField>
    <fullName>Data_Supplier_Raw_Original__c</fullName>
    <description>Data Supplier Raw Input Field (From Fugu reports)</description>
    <inlineHelpText>Data Supplier Raw Input Field (From Fugu reports)</inlineHelpText>
    <label>Data Supplier Raw Original</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Supply_Database__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date of the Buy</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Supply_Database__c/fields/Segment_Category_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Segment_Category_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Join to Segment Category Mapping</description>
    <inlineHelpText>Join to Segment Category Mapping through Segment ID.</inlineHelpText>
    <label>Segment Category Mapping</label>
    <referenceTo>Segment_Category_Mapping__c</referenceTo>
    <relationshipLabel>Supply Databases</relationshipLabel>
    <relationshipName>Supply_Databases</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Segment_Key_Raw__c.field-meta.xml
<CustomField>
    <fullName>Segment_Key_Raw__c</fullName>
    <label>Segment Key Raw</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Supply_Database__c/fields/Segment_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Segment_Mapping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segment Mapping</label>
    <referenceTo>Segment_Mapping__c</referenceTo>
    <relationshipLabel>Supply Databases</relationshipLabel>
    <relationshipName>Supply_Databases</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/07-04-2025/force-app/main/default/objects/Supply_Database__c/fields/Segment_Name_Supply_Raw__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name_Supply_Raw__c</fullName>
    <label>Segment Name (Supply) Raw</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/07-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Segment_Name_Supply_Raw_Original__c.field-meta.xml
<CustomField>
    <fullName>Segment_Name_Supply_Raw_Original__c</fullName>
    <label>Segment Name (Supply) Raw Original</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Sandbox/02-12-2025/force-app/main/default/objects/Supply_Database__c/fields/Segment_Revenue_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Segment_Revenue_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Join to Segment Revenue Transaction Object</description>
    <inlineHelpText>Join to Segment Revenue Transaction Object</inlineHelpText>
    <label>Segment Revenue Transaction</label>
    <referenceTo>Segment_Revenue_Transaction__c</referenceTo>
    <relationshipLabel>Supply Databases</relationshipLabel>
    <relationshipName>Supply_Databases</relationshipName>
    <type>Lookup</type>
</CustomField>

Sandbox/01-02-2025/force-app/main/default/objects/Supply_Database__c/fields/Target_Country_Raw__c.field-meta.xml
<CustomField>
    <fullName>Target_Country_Raw__c</fullName>
    <description>Target Country Raw Input field from Supply Database</description>
    <inlineHelpText>Target Country Raw Input field from Supply Database</inlineHelpText>
    <label>Target Country Raw</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Production/01-02-2025/force-app/main/default/classes/SupplyDatabaseHandlerTest.cls
@isTest
public class SupplyDatabaseHandlerTest {
    
    // Utility method to create test data for Supply_Database__c
    private static List<Supply_Database__c> createSupplyDatabases(Integer count) {
        List<Supply_Database__c> supplyDatabases = new List<Supply_Database__c>();
        List<Segment_Mapping__c> segmentMapping = new List<Segment_Mapping__c>();
        List<Data_Supplier_Mapping__c> dataSupMapping = new List<Data_Supplier_Mapping__c>();
        
        for (Integer i = 0; i < count; i++) {
            Supply_Database__c sd = new Supply_Database__c();
            sd.Data_Supplier_Raw_Original__c = 'SUPPLIER ' + i;
            sd.Segment_Key_Raw__c = 'SEGMENTMAPSUPPLY' + (i+1);
            sd.Segment_Name_Supply_Raw_Original__c = 'SEGMENTMAPSUPPLY' + (i+1);
            sd.Target_Country_Raw__c = 'Country ' + i;
            sd.Date__c = Date.today();
            sd.Currency_Code__c = 'USD';
            supplyDatabases.add(sd);
        }
        
        Segment_Category_Mapping__c sCM = new Segment_Category_Mapping__c();
        sCM.Segment_Name__c='Test SCM';
        insert sCM;
        
        for (Integer i = 0; i < count; i++) {
            Segment_Mapping__c sm = new Segment_Mapping__c();
            sm.Segment_Name_Sales_Raw__c = 'SEGMENTMAPSALES' + (i+1);
            sm.Segment_Name_Supply_Raw__c = 'SEGMENTMAPSUPPLY' + (i+1);
            sm.Segment_Category_Mapping__c = sCM.Id;
            segmentMapping.add(sm);
        }
        
        Account acc = new Account(
                Name = 'Test Account ',
            	Currency_Code__c = 'USD'
        );
        
        insert acc;
        
        for (Integer i = 0; i < count; i++) {
            Data_Supplier_Mapping__c dSM = new Data_Supplier_Mapping__c();
            dSM.Data_Supplier_Raw__c = 'SUPPLIER ' + i;
            dSM.Data_Supplier_Account__c = acc.Id;
            dataSupMapping.add(dSM);
        }
        
        insert dataSupMapping;
        insert segmentMapping;
        
        return supplyDatabases;
    }
    
    // Test method for before update
    @isTest
    static void testBeforeUpdate() {
        List<Supply_Database__c> supplyDatabases = createSupplyDatabases(5);
        insert supplyDatabases;
        
        Map<Id, Supply_Database__c> supplyDatabasesMap = new Map<Id, Supply_Database__c>(supplyDatabases);
        
        for (Supply_Database__c sd : supplyDatabases) {
            sd.Data_Supplier_Raw_Original__c = 'UPDATED SUPPLIER ' + supplyDatabases.indexOf(sd);
        }
        
        Test.startTest();
        update supplyDatabases;
        Test.stopTest();
        
        // Assert that data has been updated correctly
        for (Supply_Database__c sd : [SELECT Id, Data_Supplier_Raw__c FROM Supply_Database__c WHERE Id IN: supplyDatabasesMap.keySet() ORDER BY Data_Supplier_Raw__c]) {
            System.assertEquals(sd.Data_Supplier_Raw__c.contains('UPDATED SUPPLIER '), TRUE);
        }
    }
    
    // Test method for after insert/update
    @isTest
    static void testAfterInsertUpdate() {
        List<Supply_Database__c> supplyDatabases = createSupplyDatabases(5);
        
        Test.startTest();
        insert supplyDatabases;
        Test.stopTest();
        
        Map<Id, Supply_Database__c> supplyDatabasesMap = new Map<Id, Supply_Database__c>(supplyDatabases);
        
        // Perform assertions as needed
        for (Supply_Database__c sd : [SELECT Id, Segment_Revenue_Transaction__c FROM Supply_Database__c WHERE Id IN: supplyDatabasesMap.keySet()]) {
            // Example assertion: Ensure the Segment_Revenue_Transaction__c field is set correctly
            System.assertNotEquals(null, sd.Segment_Revenue_Transaction__c);
        }
    }
    
    
    // Test method for after delete
    @isTest
    static void testAfterDelete() {
        List<Supply_Database__c> supplyDatabases = createSupplyDatabases(5);
        insert supplyDatabases;
        
        Map<Id, Supply_Database__c> supplyDatabasesMap = new Map<Id, Supply_Database__c>(supplyDatabases);
        Set<Id> segmentRecTransactionIds = new Set<Id>();
        
        for(Supply_Database__c suppDatabase : [SELECT Id, Segment_Revenue_Transaction__c FROM Supply_Database__c WHERE Id IN: supplyDatabasesMap.keySet()]){
            segmentRecTransactionIds.add(suppDatabase.Segment_Revenue_Transaction__c);
        }
        
        Test.startTest();
        delete supplyDatabases;
        Test.stopTest();
        
        // Perform assertions as needed
        for (Segment_Revenue_Transaction__c segmentRevTransaction : [SELECT Id, Uniques_RollUp__c FROM Segment_Revenue_Transaction__c WHERE Id = :segmentRecTransactionIds]) {
            System.assertEquals(segmentRevTransaction.Uniques_RollUp__c, 0);
            
        }
        
        
    }
    
    // Test method for undelete
    @isTest
    static void testUndelete() {
        List<Supply_Database__c> supplyDatabases = createSupplyDatabases(5);
        insert supplyDatabases;
        
        Map<Id, Supply_Database__c> supplyDatabasesMap = new Map<Id, Supply_Database__c>(supplyDatabases);
        Set<Id> segmentRecTransactionIds = new Set<Id>();
        
        for(Supply_Database__c suppDatabase : [SELECT Id, Segment_Revenue_Transaction__c FROM Supply_Database__c WHERE Id IN: supplyDatabasesMap.keySet()]){
            segmentRecTransactionIds.add(suppDatabase.Segment_Revenue_Transaction__c);
        }
        
        delete supplyDatabases;
        
        Test.startTest();
        Undelete supplyDatabases;
        Test.stopTest();
        
        // Perform assertions as needed
        for (Segment_Revenue_Transaction__c segmentRevTransaction : [SELECT Id, Uniques_RollUp__c FROM Segment_Revenue_Transaction__c WHERE Id = :segmentRecTransactionIds]) {
            System.assertNotEquals(null, segmentRevTransaction.Uniques_RollUp__c);
            
        }
    }
}